openfl/lime

- lime/graphics/Image.hx
Tiny typo caused creation of a BitmapData to always crash.
> Issue #304: Prevent crash when creating a new BitmapData.

- legacy/project/src/common/Surface.cpp
This only happens when the BitmapData does not have an alpha component, such as from a loaded JPG.
As far as I can tell, this code should never have been here as it causes getPixels() to modify the BitmapData its getting the pixels from. It looks like either:
1. Someone was using it for testing to visually verify it was grabbing pixels from where they expected.
2. It was trying to get the alpha value in the returned pixels to 0xFF, but doing it wrong. And, that's not even necessary because without this, it already returns an alpha of 0xFF.
I also have a bunch of unit tests to go along with this change, but I can't submit those yet because they don't work on -next as that appears to use RGBA instead of ARGB like legacy does.
> Fixed BitmapData.getPixels() to not change the image to turn it blue.

- legacy/templates/iphone/PROJ/Images.xcassets/AppIcon.appiconset/Contents.json
- legacy/templates/iphone/PROJ/Images.xcassets/LaunchImage.launchimage/Contents.json
- templates/iphone/PROJ/Images.xcassets/AppIcon.appiconset/Contents.json
- templates/iphone/PROJ/Images.xcassets/LaunchImage.launchimage/Contents.json
- tools/platforms/IOSPlatform.hx
This fixes https://github.com/openfl/openfl/issues/463 and as a bonus enables apps to run at the native resolution on iPhone 6 and iPhone 6 Plus, as proper launch images are required for that.
> Adds all launch image and icon sizes wanted by XCode

- legacy/project/src/iPhone/System.mm
This seems to make things happy on armv7, arm64, and simulator.
Not sure why this was "suddenly" a problem.  Maybe something different in iOS 8?
See https://github.com/openfl/lime/issues/327
> resolves https://github.com/openfl/lime/issues/327

- lime/app/Config.hx
- lime/system/System.hx
- templates/haxe/ApplicationMain.hx
- templates/haxe/DefaultAssetLibrary.hx
Allow users to specify custom resources root in lime.embed.
This PR resumes the discussion at http://community.openfl.org/t/set-root-url-for-resources-on-html5-backend/580/3
I've added an extra `assetsPrefix` argument to `lime.embed`, which can be used to specify custom prefix for assets location (such as `/static/app/resources/` or `https://static.my.magic.domain/app-resources/`).
>A part of me considers doing it as another argument, but another part of me wonders if we'll have another things we want to do to customize it, and we keep (perpetually) adding arguments when (at some point) we should have done some kind of "options" object.
I decided to make it as an another argument, because it's less disruptive. Making some kind of "options" object is definitely great idea, but it's out of …
> Support custom prefix (root) for resources URLs in html5.

- lime/tools/helpers/FlashHelper.hx
This fix is very important and avoid a very vicious situation we encountered...
We have an architecture where an openfl application is composed by multiples clients which are individual openfl projects themselves.
So each of these individual proejcts had their own bin directory, and now the bin/obj/assets.swf file !
That lead us to the main project compilation, templates were copied perffectly and the generation is good. BUT the wrong assets.swf file was used by haxe  !  As several classpath lead to the same file, things where mixed up and very hard to catch. (since not all the ressources where common).
Anyway, the idea is to clarify which assets.swf file must be linked to our final flash file!
For that, I'm proposing an easy but not elegant way here using  full path.
But you can also, …
> Security fix

- lime/tools/helpers/FlashHelper.hx
Just added a simple fallback in case the font name could not be parsed properly (we have such font here, homemade).
Haven't been able to debug the lime code directly, so meanwhile I though that fallback could be helpful
> Added fallback to filename when font name couldn't be parsed

- lime/utils/ByteArray.hx
Originally, I encountered this problem when I was playing with luxeengine - https://github.com/underscorediscovery/snow/pull/68
Since ByteArray in show was based on ByteArray from lime, I checked lime's version, and found the same bug.
I don't know exact lime roadmap (will lime still use it own implementation of ByteArray or will use typedarrays like snow), but maybe this pull-request will be useful.
---
Prehistory: let's have an empty ByteArray, and then do writeByte in a loop.
value | allocated | action
--- | --- | ---
- | 0 | initial
1 | 1 | up resize
2 | 2 | up resize
3 | 4 | up resize
4 | 4 | -
5 | 8 | up resize
6 | 6 | down resize
7 | 12 | up resize
8 | 8 | down resize
9 | 16 | up resize
10 | 10 | down resize
... | ... | ... etc ...
> Fix ByteArray resizing for js target

- lime/_backend/html5/HTML5Window.hx
When mouse wheel moved up 1 notch, deltaY is:
- HTML5
- Chrome : -100 (deltaMode=0) (Chrome40.0.2214.115m, Windows7)
- Chrome : -33.333 (deltaMode=0) (Chrome40.0.2214.115m, Windows8.1, laptop touchpad)
- Firefox : -3 (deltaMode=1) (Firefox36, Windows7)
- Firefox : -1 (deltaMode=1) (Firefox35, Windows8.1, laptop mouse)
- Firefox : -0.2 (deltaMode=1) (Firefox36, Windows8.1, laptop touchpad)
- Firefox : -0.75 (deltaMode=1) (Firefox35, Windows7, notchless wheel)
- Flash : 3
- Windows : 1
> Fix direction of mouse wheel deltaY on HTML5

- legacy/project/src/sdl2/SDL2Stage.cpp
Tested with 3 simultaneous joypads and deconnection+reconnection scenario. Thanks to Alan McCosh for pointing this out.
> joystick connection accounting fix

- lime/system/System.hx
I have forgotten to make this pull request.
It should be better to require bindings module from ndll.js, not from ApplicationMain.js.
https://github.com/vroad/node-ndll/blob/a3268e66094170fb7147d7a807a1867d24156a78/ndll.js
> Fix require('ndll')

- templates/haxe/DefaultAssetLibrary.hx
Fix isLocal function always true with test Sound on Flash.
When embed sound is set on false, isLocal can't by pass exist test.
In the original case, exist test is by passed with Flash compilation and true is return.
> isLocal always true with Sound [Flash]

- js/Boot.hx
Resolve the error `Not_found` for haxe 3.2 on html5 target.
> Fix js/Boot.hx for haxe 3.2

- lime/_backend/flash/FlashMouse.hx
- lime/_backend/flash/FlashWindow.hx
- lime/_backend/html5/HTML5Mouse.hx
- lime/_backend/html5/HTML5Window.hx
- lime/_backend/native/NativeMouse.hx
- lime/_backend/native/NativeWindow.hx
- lime/ui/Mouse.hx
- lime/ui/Window.hx
- project/include/ui/Mouse.h
- project/include/ui/Window.h
- project/src/ExternalInterface.cpp
- project/src/backend/sdl/SDLMouse.cpp
- project/src/backend/sdl/SDLWindow.cpp
- project/src/backend/sdl/SDLWindow.h
This pull request contains 3 things:
- `lime.Mouse.lock`, a boolean that hides the cursor and prevents it from leaving the window. AFAIK there isn't a way to keep the cursor from being hidden using `SDL_SetRelativeMouseMode`
- `lime.Mouse.globalWarp`, a function that warps the cursor anywhere in screen space
- `window.warpMouse`, a function that warps the cursor anywhere in window space
Not having relative mouse motion events is mitigated by having window.warpMouse, as users can log the position of the mouse after it moves and then warp it back to the center. It is worth noting, however, that both of the warp functions will fire a `mouseMove` event.
> Adding mouse functionality for locking/warping in native

- legacy/project/src/opengl/OpenGLContext.cpp
Change lime legacy default alpha blending blendFunc to correctly blend alpha for RGBA textures in non-premultiplied alpha mode
> Improve legacy default alpha blending

- lime/graphics/Image.hx
- lime/graphics/utils/ImageDataUtil.hx
I've tested this on a wide range of bitmap images (including randomly generated ones) and it is confirmed accurate. I tried a few more "optimized" versions than this but the gains were marginal, the code was much more complex, and failed on edge cases. Best to keep it simple -- if this needs to be sped up, it could be dropped into C++ via CFFI.
> BitmapData: added getColorBoundsRect implementation for next

- project/src/text/Font.cpp
As discussed in openfl/openfl#665
Also found that a call to SetSize prior to Decompose causes unexpected results due to transformation matrix being set. Will resetting it before decomposition have any unwanted side effects?
> Added cubic support to font decomposition and xform reset fix

- lime/graphics/cairo/CairoSurface.hx
- project/src/utils/ByteArray.cpp
This line prevented us from compiling for nodejs since on nodejs Uint8Array does not contain ByteArray.
I've also found strange #if in SimpleImage example. I don't know what this does because the example just works fine without that #if.
https://github.com/vroad/lime-samples/blob/master/SimpleImage/Source/Main.hx#L117
> Fix problem with cairo on nodejs

- lime/graphics/cairo/Cairo.hx
- lime/graphics/cairo/CairoFont.hx
- lime/graphics/cairo/CairoFontOptions.hx
- lime/graphics/cairo/CairoHintMetrics.hx
- lime/graphics/cairo/CairoHintStyle.hx
- lime/graphics/cairo/CairoSubpixelOrder.hx
- lime/text/Font.hx
- lime/text/TextLayout.hx
- project/Build.xml
- project/src/graphics/cairo/CairoBindings.cpp
- project/src/text/Font.cpp
- project/src/text/TextLayout.cpp
Implemented some missing bindings.
I had to also disable what appears to be super sampling on the horizontal axis in the Font class. It looks like it was put there to make the GL text renderer nicer but it was interfering with Cairo's text renderering. If we decide to go with Cairo for text renderering under GL then it won't matter.
Requires native-toolkit/cairo#1
> Work on Cairo FreeType implementation

- lime/_backend/native/NativeRenderer.hx
- lime/graphics/GLRenderContext.hx
- lime/graphics/cairo/Cairo.hx
- project/src/backend/sdl/SDLRenderer.cpp
- project/src/backend/sdl/SDLRenderer.h
Also added EXT_bgra constants. I check for this extension before falling back to a slower method in the OpenFL OpenGL / Cairo hybrid renderer.
> Handle window resize for Cairo

- project/include/text/TextLayout.h
- project/src/text/TextLayout.cpp
I had a feeling that TextLayout was very slow for some reason.
I ran VS2013's profile and found that ```hb_shape_plan_create_cached``` is taking too much time.
Fortunately I found a fix for this soon.
> Fix high cpu usage in TextLayout

- legacy/project/src/common/TextField.cpp
For some reason calling "iswalpha" and "isdigit" with korean unicode chars makes apps crash.
To reproduce modify the "AddingText" example and set the text to something like "한국어 조선말", it will crash on Blackberry.
This pull request fixes that problem.
> [Legacy] Fix Blackberry crash when calling system's "iswalpha" or "isdigit"

- legacy/project/src/common/Audio.cpp
Hi. This is clearly a typo since wave_data.subChunkSize (undefined) was used instead of wave_format.subChunkSize obtained from the fread. I am not sure about the extra 16 bytes, but this fixes my BWF files (just skips the chunk) and should not affect the normal WAV files.  Thanks.
> Fix skipping BEXT Chunk (BWF format in .wav)

- legacy/templates/android/template/src/org/haxe/lime/MainView.java
- templates/android/template/src/org/libsdl/app/SDLActivity.java
More info - http://community.openfl.org/t/solved-fps-drop-on-android-when-moving-finger-around-the-screen-legacy/1564
> Fix FPS drop when finger is moved around the screen on older android phones

- legacy/project/src/sdl2/SDL2Stage.cpp
Fix for https://github.com/openfl/lime/issues/360
Tested on a Dell XPS 13 with touchscreen on Linux with XInput2 driver.
Please note that this also requires changing SDL_Config in "project/lib/sdl" to enable XInput2, as follows:
```
diff --git a/include/configs/linux/SDL_config.h b/include/configs/linux/SDL_config.h
index 99b06c2..ba75343 100644
--- a/include/configs/linux/SDL_config.h
+++ b/include/configs/linux/SDL_config.h
@@ -274,14 +274,14 @@
#define SDL_VIDEO_DRIVER_X11_DYNAMIC_XEXT "libXext.so.6"
/* #undef SDL_VIDEO_DRIVER_X11_DYNAMIC_XCURSOR */
/* #undef SDL_VIDEO_DRIVER_X11_DYNAMIC_XINERAMA */
-/* #undef SDL_VIDEO_DRIVER_X11_DYNAMIC_XINPUT2 */
+#define SDL_VIDEO_DRIVER_X11_DYNAMIC_XINPUT2 "libXi.so.6"
/* #undef SDL_VIDEO_DRIVER_X11_DYNAMIC_XRANDR */
/* #undef …
```
> [legacy] Add finger touch events to SDL2Stage

- dependencies/webgl-debug.js
`glFunctionArgToString` in webgl-debug.js was broken for null and undefined arguments.
In fact the whole thing looks pretty old. We should maybe consider updating to the [newer version by Kronos](https://www.khronos.org/registry/webgl/sdk/devtools/src/debug/). *Buut* haven't tested that in replace, so just patched this simple bug for now :P.
> fixed: webgl errors involving null/undefined arguments break the whole process

- legacy/project/src/common/Surface.cpp
When you see it... :)
(I don't see any equivalent on V2, but if there was any copy&paste maybe we should double check that too).
> Fix legacy Surface.BlitChannel source rect

- project/src/backend/sdl/SDLApplication.cpp
- project/src/ui/TouchEvent.cpp
Adds touch support in SDLApplication (regular lime, not legacy).
However I am experiencing crashes as soon as a touch event comes in, with no output.
So far I saw it reach IModule.onTouchStart but did not reach my test app's event handler.
Still needs debugging to find out where the crash happens.
> Implement touch support in SDLApplication

- templates/compatibility/DefaultAssetLibrary.hx
- templates/haxe/DefaultAssetLibrary.hx
`Assets.loadImage`, `loadText` and `loadBytes` were all sync and didn't support non-embedded assets.
This fixes https://github.com/openfl/openfl/issues/369.
> fixed: html5 async asset loading

- templates/android/template/src/org/libsdl/app/SDLActivity.java
The coordinates are already relative to the display so they should be
kept as such when passing them to SDL native.
> Fix touch coords in Android SDLActivity

- lime/_backend/native/NativeApplication.hx
Gamepad connect can fire twice in a row the event for the same device (tested on Mac OSX). Prevent that.
> Guard against doppleganger gamepad connection

- project/src/backend/sdl/SDLApplication.cpp
Added gamepad controller axis deadzone low filter, removing unnecessary spam from controller analog sticks natural jitter.
Base filter set default at value 1000. Tested with multiple gamepads connected at the same time (Sony PS3).
> Gamepad controller axis deadzone low filter

- templates/haxe/DefaultAssetLibrary.hx
Currently images are loaded with the id as the source. This should be the path instead.
> Fixed html5 image loading through DefaultAssetLibrary where id and path doesn't match

- lime/app/Preloader.hx
- templates/haxe/DefaultAssetLibrary.hx
Embedding fonts for Android isn't currently working as the assets for CPP targets aren't embedded anywhere. NOTE: I've only tested for Android with Fonts. To recreate this issue, create the TextMetrics sample project. Set the assets to embed in the project.xml and try to compile.
Edit: Added failsafe to Preloader for small AIR binaries. Sometimes the the on complete handler would miss the dispatch, which causes the app to be stuck on the preloader screen. I've added a simple check in the enterframe loop to prevent the app from getting stuck.
> Fixed CPP target embedded assets

- lime/tools/helpers/IOSHelper.hx
Hi,
This commit allows you to choose the device like this:
```
openfl test ios -simulator -ipad-2
```
Available devices are :
iphone-4s, iphone-5, iphone-5s, iphone-6-plus, iphone-6, ipad-2, ipad-retina, ipad-air
Old flag "-iphone" map to "-iphone-6"
Old flag  "-ipad" map to "-ipad-air"
Jonas
> add device choice for ios simulator

- lime/_backend/flash/FlashWindow.hx
- lime/_backend/html5/HTML5Window.hx
- lime/_backend/native/NativeWindow.hx
- lime/ui/Window.hx
- project/include/ui/Window.h
- project/src/ExternalInterface.cpp
- project/src/backend/sdl/SDLWindow.cpp
- project/src/backend/sdl/SDLWindow.h
I needed to change native window title in runtime.
SDL only, not implemented for HTML5, nor Flash.
My first lime contribution, works for me like that, should be reviewed.
> settable lime.ui.Window.title, SDL only

- project/src/backend/sdl/SDLApplication.cpp
Cater for two's complement in joypad analog axis - positive analog and triggers would otherwise send wrong value if divided by 32768 when 32767 is max.
> Cater for two's complement in joypad analog axis

- lime/_backend/flash/FlashApplication.hx
- lime/app/Config.hx
- lime/system/System.hx
I've added simple AIR detection for the lime FlashBackend. I really don't know if this is the best approach to take. I tried keeping the processing low by only doing the AIR check once within the backend itself. Then within the System class added handling of the "flash" compile directory getters.
It would be nice if we could cache ```Type.resolveClass("flash.filesystem.File")``` as it will always resolve the same.
> Added AIR detection to FlashBackend and toplevel directory paths.

- lime/project/ProjectXMLParser.hx
- lime/tools/platforms/MacPlatform.hx
I figured out why when doing a cross build hxcpp's ndll where trying to be copied,
it was coming from these three lines https://github.com/openfl/lime/blob/master/include.xml#L52-L54
cpp was defined incorrectly instead of neko.
Also a fix for the mac template folder name, since linux is case sensitive.
> Fix desktop cross build

- lime/_backend/flash/FlashApplication.hx
- lime/_backend/html5/HTML5Application.hx
Extending key mappings in Flash and HTML5 targets, based on the constants listed in the [AS3 Keyboard class reference] (http://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/ui/Keyboard.html).
Both targets tested in Safari.
> Additional key mappings for Flash and HTML5 targets

- lime/tools/helpers/NodeJSHelper.hx
Now we should use "node" for running lime app, as two projects are recently merged and "iojs" command is removed from distribution.
> Use "node" instead of "iojs"

- lime/tools/platforms/WindowsPlatform.hx
Terminal typically displays a permission problem with ReplaceVistaIcon.exe on cross-compilation. ReplaceVistaIcon.exe is not a native application for Linux or Mac, however It appears that 
PlatformHelper.hostPlatfrom == WINDOWS (old file)
is registered as always TRUE regardless of host platform, so adding an Import for lime.project.Platform registers the correct TRUE or FALSE for 
PlatformHelper.hostPlatform == Platform.WINDOWS (pull request)
> Fixed icon issue on cross-compilation

- tools/utils/PlatformSetup.hx
When attempting to run `haxelib run lime setup linux` on Ubuntu versions after 13.10, such as Ubuntu 14.04, Lime crashes since there is no *ia32-libs-multiarch* package available. The issue with this line of code is that it only checks for Ubuntu 13.10, and not any versions after this. This means that when running this command on any version of Ubuntu after 13.10, Lime will attempt to install the *ia32-libs-multiarch* package, which doesn't exist as of Ubuntu 13.10.
Fortunately, Haxe supports testing strings via comparison operators.
By replacing the `==` operator with `>=`, this line now instead checks for versions of Ubuntu at or after 13.10 Saucy Salamander.
This works on Ubuntu 14.04.1, and should work on other versions too. Versions of Ubuntu Before 13.10 should still stay the same; …
> Fixed "lime setup linux" on Ubuntu versions after 13.10 

- lime/tools/platforms/IOSPlatform.hx
- lime/tools/platforms/TVOSPlatform.hx
- lime/ui/Window.hx
- project/Build.xml
- templates/haxe/DefaultAssetLibrary.hx
I've fixed a few bugs in the tvOS implementation and force the iOS target to use ARC as SDL takes it for granted and some of the files of the latest revisions won't compile if it's not enabled for iOS/tvOS targets.
> Minor fixes for tvOS + ARC

- lime/_backend/native/NativeApplication.hx
On nodejs onExit event is not dispatched, and it's problematic to call ```Sys.exit()``` on nodejs because calling that will result in closing app without doing cleanup.
> Do not use Sys.exit on nodejs as it closes the app without cleanup

- legacy/project/src/sdl/SDLStage.cpp
If `virtualkeyboard_change_options()` is not called, whenever the user requests the virtual keyboard the last one used by the operating system will be displayed. For instance, if the user unlocks the phone (numeric layout), goes directly to a Lime / OpenFL application and requests the keyboard, the one displayed will be the numeric one.
> Legacy: Fixes virtual keyboard on BlackBerry

- lime/tools/platforms/TVOSPlatform.hx
- templates/tvos/PROJ.xcodeproj/project.pbxproj
I had some issues getting the flag to be set at all. Plus, considering that apps compiled without it will not even run on the devices I can't see any reason for keeping it around.
> Dropped flag for toggling bitcode on tvOS builds

- templates/tvos/PROJ.xcodeproj/project.pbxproj
Adds flags for testability, only to build active architecture, and bakes the app package name into the project file. All this to fix warnings generated by XCode.
This also drops the flags for architecture completely as there is only one valid variation for tvOS and not setting it gives the default.
> Several changes to the XCode project template to fix warnings

- lime/tools/platforms/WindowsPlatform.hx
Recent Merge on Hxcpp may prevent 64bit machine users from compiling 32bit binary. Though the work around may be as easy adding compilation flag: -32.
Through this pull, OpenFl and Lime can now recover its usual compilation procedure.
> Fix cross-compilation Halt on 64bit Machine

- legacy/project/src/common/FreeType.cpp
iOS 8.2 changed the system font directory (now several directories).
Since then text rendering of built-in fonts (_sans etc) has not worked with legacy.
> fixed: system fonts did not load on modern iOS with legacy lime

- lime/tools/helpers/StringHelper.hx
If you look at the template context generated by OpenFL, you notice a bunch of odd names for variables:
SET_H_OMEDRIVE
SET_P_ROCESSOR__IDENTIFIER
SET_P_ROCESSOR__REVISION
SET_L_OCALAPPDATA
SET_N_EKO__INSTPATH
...and so on.
These odd names are caused by taking an already-uppercase string and running it through `formatUppercaseVariable()`. For instance, if you run `formatUppercaseVariable("NEKO_INSTPATH")`, it adds an underscore after the first letter and another after the existing underscore, giving "`N_EKO__INSTPATH`."
This pull request fixes both bugs.
> formatUppercaseVariable() shouldn't mess up already-uppercase strings.

- legacy/project/src/common/FreeType.cpp
Both Core/ and CoreAddition/ must be searched as they seem to vary between iOS version and individual device
> fixed: font paths inconsistent between iOS installs

- lime/tools/helpers/NekoHelper.hx
During Cross-Compile from Linux to Windows, Neko Compilation chain will normally call into ReplaceVistaIcon.exe, unfortunately, EXE files are not native applications of NON-Windows systems, thus a permission issue occurs.
By indicating to the Source Code that ReplaceVistaIcon.exe be called only when it detected Windows systems through 
PlatformHelper.hostPlatform == Platform.WINDOWS
The issue is fixed.
> Fixes Icon Issue on Neko Cross Compile Linux to Windows, fix openfl/lime#626

- project/src/system/JNI.cpp
This is related to Android Extensions.
It looks like HaxeToJNIArgs creates some references that need to be cleaned up. Pushing and Popping a local frame seems to fix this. This fix is only for CallStatic(...) and it is very possible a similar issue exists with the other JNI functions.
Without this fix, after 512 arguments passed into CallStatic, the app will crash. 
Fix for: https://github.com/openfl/lime/issues/644
> Cleaning up leaked references in JNI caused by function arguments

- lime/system/Display.hx
- lime/system/System.hx
- project/include/system/System.h
- project/src/ExternalInterface.cpp
- project/src/backend/sdl/SDLSystem.cpp
This seems like it would be useful for various platforms.
Unfortunately, it doesn't seem to be aware of display scaling in win8/10 -- it just returns "96" for everything on my system regardless of display scale. But perhaps it will work nicely on other platforms until we can figure out what's going on with Win8/10.
> Expose display device DPI

- project/src/backend/sdl/SDLRenderer.cpp
On cpp, readPixels returns an image with alpha=0. Can be tested with:
```haxe
package;
import flash.display.Bitmap;
import flash.display.BitmapData;
import flash.events.MouseEvent;
import flash.Lib;
import lime.app.Application;
import lime.math.ColorMatrix;
import lime.math.Rectangle;
import openfl.display.Sprite;
import openfl.events.Event;
class Main extends Sprite {
public function new () {
super ();
var gfx = this.graphics;
gfx.beginFill(0xff0000);
gfx.drawCircle(Lib.current.stage.stageWidth/2, Lib.current.stage.stageHeight/2, 200);
gfx.endFill();
addEventListener(MouseEvent.MOUSE_DOWN, readPixels);
addEventListener(Event.ADDED_TO_STAGE, readPixels);
}
function readPixels (_) {
var img = Application.current.renderer.readPixels();
var spr = new Sprite();
spr.scaleX = spr.scaleY = 0.5; …
```
> Renderer.readPixels fix

- project/src/ExternalInterface.cpp
We noticed a memory leak in iOS when getting the system application directory. The underlying string is never freed.
I'm not sure if this is the best place for this, but it does fix the leak. Happy to discuss alternatives since it seems like it should be closer to `alloc_string`
@jgranick
> Fix system dir string leak

- lime/tools/helpers/TVOSHelper.hx
- templates/tvos/PROJ/haxe/Build.hxml
- templates/tvos/PROJ/haxe/makefile
Forces the architecture to be 64 bit only when using the simulator.
Also fixes an issue where it was being set the wrong define thus not allowing to build for the simulator as expected.
> Fixes for tvOS.

- lime/audio/openal/AL.hx
- project/src/audio/openal/OpenALBindings.cpp
Fixes OpenAL bindings on Neko.
Additionally, corrects al.sourceQueueBuffer so it sends an Array<Int> and not a Dynamic.
> OpenALBindings: Converted val_array references to be neko compatible.

- lime/graphics/ImageBuffer.hx
If you don't initialize Bool field in constructor, it will become undefined on dynamic targets. Undefined and false are not the same thing, so it may cause issues.
> Initialize premultiplied in ImageBuffer's constructor

- project/include/app/Application.h
- project/include/graphics/Renderer.h
- project/include/ui/Window.h
Not defining virtual destructors in these classes will cause memory leaks in subclasses, since destructors of subclasses are not called if it's not declared as virtual in base class.
https://github.com/openfl/lime/blob/b3164fa16143dc0dcc97fecf6cc2a1f7c43a79df/project/src/ExternalInterface.cpp#L92-L93
This will only call `Window`'s destructor if it's not virtual. To fix memory leaks, you need to cast window instance to SDLWindow, or define virtual destructor in base class. I think there is no reason to do former though.
> Implement virtual destructors in some C++ classes

- lime/graphics/format/PNG.hx
Fix the missplaced #end macro that prevented html5 encoding from working
Fix bytearray array access
> Fix png encoding in the html5 target

- lime/graphics/Image.hx
It was setting the source rect x and y to the dest x and y and not subtracting it.
> Fix Image.copyPixels() with negative dest

- lime/tools/platforms/TVOSPlatform.hx
This allows lime extensions to add things like:
This is the only missing extension, since dylib packages are deprecated and replaced by TBD on xcode 7+
> Allow to include TBD dependencies in XML for tvOS

- tools/utils/PlatformSetup.hx
Newer hxcpp require a newer ndk (see http://community.openfl.org/t/lime-rebuil-android/7273/5),
using it on linux without issue.
Might want to update the sdk too, I think the update procedure does that too anyway,
but haven't tested it so I left it for now.
> Updating android ndk version

- templates/haxe/DefaultAssetLibrary.hx
Fix https://github.com/openfl/openfl/issues/723
Allows the usage of `setCwd` without breaking the asset loading.
> Load assets from next of the executable

- tools/CommandLineTools.hx
To modify the project config through the command line,
for instance `lime build linux --config-cpp.requireBuild=false`,
doesn't work with Reflect.setField since it doesn't do it recursively on the `.` like config.set,
so this add a special case to make it work.
> Allow modification of project config in the command line

- lime/graphics/utils/ImageDataUtil.hx
- project/src/graphics/utils/ImageDataUtil.cpp
Previously fillColor would get multiplied repeatedly in a loop, this PR aims to fix it by computing the premultiplied alpha value once, and using it in calls to fillColor.writeUInt8 with the premultiplied arg set to false.
See #759 and #631
> Fix fillRect behaviour when using alpha on neko/cpp (see #759 and #631)

- lime/graphics/opengl/ExtensionBGRA.hx
- lime/graphics/opengl/ExtensionPackedDepthStencil.hx
Instead of adding those constants to `GL` class directly, I added those to separate classes. WebGL does something like this to handle extension constants/functions.
> Add ExtensionBGRA and ExtensionPackedDepthStencil

- tools/utils/PlatformSetup.hx
This adds support for the default package managers of Gentoo, Sabayon, and Fedora >= 22
> Add support for DNF, Equo, and Emerge to PlatformSetup

- lime/ui/Window.hx
Simple typo that needed correcting, so that people can have the ability to change the title of the window if need be.
> Correct window.title setter

- lime/project/ProjectXMLParser.hx
This code checks for the existence of `FLASH_PLAYER_EXE` but copies `SWF_PLAYER` instead. Also, fixing this typo isn't enough, since [`FlashHelper` looks in the system environment variables](https://github.com/openfl/lime/blob/develop/lime/tools/helpers/FlashHelper.hx#L959), not `project.environment`, for a value named `FLASH_PLAYER_EXE`.
I've created two pull requests for you to choose from:
1. Deletes the code. #812
2. Fixes the typo and calls `Sys.putEnv()`. #813
Personally, I suggest option 1. No one will ever need to set `FLASH_PLAYER_EXE` from project.xml, since they can get exactly the same result by setting `SWF_PLAYER`. This code is just taking up space.
> FLASH_PLAYER_EXE typo fix (option 1)

- lime/tools/platforms/AndroidPlatform.hx
The directive <java path="....  stopped working since it was placing the files under the wrong folder for gradle.
> Fix folder for <java path="...." if="android" /> directive

- templates/haxe/DefaultAssetLibrary.hx
`isLocal `returns true everytime for other target than flash
But it is wrong, if some assets are not in **project.xml**, they are obviously not embedded and you'll need to load asynchronously (so `isLocal `has to return `false`).
This PR fixed this partially.
I say 'partially" because if you add sounds in **project.xml** with `embed=false`, they will be in the variable `path` and isLocal will still return true even if you choose embed=false. I think there is a bug somewhere that consider some files to be embedded even if they are not.
Also, I think we could avoid casting 2 times `AssetType` (in Assets.hx and DefaultAssetLibrary.hx). We just need to pass AssetType as a function parameter like this instead of using String: 
`public override function isLocal (id:String, type:AssetType):Bool`
> should fix isLocal when using not embedded assets on html5 and cpp

- templates/android/template/app/src/main/AndroidManifest.xml
When building for android -debug, raises this error:
```
*Avoid hardcoding the debug mode; /android:debuggable= "true"/ leaving it out allows debug and release builds to automatically assign one*
```
**According to sdk guide line:**
Support for a true debug build. Developers no longer need to add the  android:debuggable attribute to the  <application> tag in the manifest — the build tools add the attribute automatically. In Eclipse/ADT, all incremental builds are assumed to be debug builds, so the tools insert  android:debuggable="true". When exporting a signed release build, the tools do not add the attribute. In Ant, a ant debug command automatically inserts the android:debuggable="true" attribute, while ant release does not. If android:debuggable="true" is manually set, then ant …
> Fix Android compilation using debug

- lime/_backend/html5/HTML5AudioSource.hx
On some cases, it ended up sending negative positions crashing the game.
> Avoid howlerjs exception when seeking files that are being played.

- lime/tools/platforms/AndroidPlatform.hx
- templates/android/template/app/build.gradle
Currently, Lime renames it before installing, but this can be annoying for people who only use the `build` command.
> Make Gradle use the right APK filename.

- project/src/backend/sdl/SDLRenderer.cpp
This pull request fixes OpenFL 4.x [rendering problem](https://github.com/openfl/openfl/issues/1309) occurred in iPhone 6 Plus and 6s Plus.
> Fix SDL renderer scale calculation error

- lime/_backend/html5/HTML5Window.hx
- lime/system/Clipboard.hx
Because of various "security" related reasons, a hidden `<input>` is required, having selected text in order for Copy, and Cut events to be fired.
Only within such an event handler can the user (OpenFL) write to the system clipboard.
> Implement HTML5 System clipboard support

- project/src/backend/sdl/SDLJoystick.cpp
The SDL implementation of IOS Accelerometer was correct.  Wrapped around the Joystick API for commodity I guess, but working.
The problem was in fact that LIME didn't linked the joystick itself...
After few long hours, the obvious was found, the define was wrong.   IPHONE instead of IOS did fix the problem.
> Fix the IOS Accelerometer which wasn't fully linked to lime

- lime/project/HXProject.hx
When Lime finds a project.hxp file, it runs `HXProject.fromFile()` to parse it. This function runs these two lines:
```haxe
ProcessHelper.runCommand ("", "haxe", [ name, "-main", "lime.project.HXProject", "-cp", tempDirectory, "-neko", nekoOutput, "-cp", PathHelper.combine (PathHelper.getHaxelib (new Haxelib ("lime")), "tools"), "-lib", "lime", "-D", "lime-curl", "-D", "native", "-D", "lime-native", "-D", "lime-cffi" ]);
ProcessHelper.runCommand ("", "neko", [ FileSystem.fullPath (nekoOutput), HXProject._command, name, Std.string (HXProject._target), Std.string (HXProject._debug), Serializer.run (HXProject._targetFlags), Serializer.run (HXProject._templatePaths), Serializer.run (HXProject._userDefines), Serializer.run (HXProject._environment), temporaryFile ]);
```
The first line compiles …
> Fix HXP projects.

- lime/utils/AssetCache.hx
- lime/utils/AssetLibrary.hx
- lime/utils/AssetType.hx
- lime/utils/Assets.hx
Here's a small part of https://github.com/openfl/lime/pull/850 re-applied to latest development after the 6600 line change Asset.hx commit (61fec3eefe696e880e2200186004ec95a214aa8c).
There's more valuable code that builds on top of these changes, like:
- even more code de-duplication
- (pre)loader improvements for HTML5
- actually using the contents of generated `library.json`  and  `library.dat` files, which will allow reducing DefaultAssetLibrary to almost nothing.
- prevent double loading of assets and libraries, which may happen when calling `Assets.load* ()` multiple times in a single function
But, until I've had some feedback if this refactoring is in the desired direction, I won't restart working on the above.
> Refactor Assets.hx

- lime/_backend/html5/HTML5HTTPRequest.hx
This pull request makes sure that using XmlHttpRequest in Internet explorer, does not give an excection.
> Make XMLHttpRequest work on Internet Explorer 11 also.

- lime/app/Preloader.hx
- lime/text/Font.hx
- lime/utils/AssetLibrary.hx
In latest OpenFL / Lime version preloader din't work as earlier. This PR tries to fix it.
Additionally it adds trace of error, because without it is very difficult to guess why game is not loading (usually this is related because howler can't load .wav or .ogg sound; interestingly, it was working earlier with soundjs, but this is another story...)
It seems that Safari reports that font loaded while font **IS NOT** actually loaded. There are 2 identical `TextView`'s, first is added immediately, second after some timeout:
This is reproduced with last OpenFL / Lime version, this **IS NOT** related to font preloading issue fixed in https://github.com/openfl/lime/commit/4e8bc030f6f15fed7d0f095ba323990658ca66bf. This happens only in Safari.
Demo: …
> 1. More precise preloader for html5; 2. Fix font preloading in Safari.

- tools/utils/PlatformSetup.hx
The `ia32-libs-multiarch` was removed since ubuntu 13.10,
asking to install it will make `openfl setup linux` fail.
See https://github.com/openfl/openfl/issues/627
Though maybe we'd need to install something else instead,
I'll set up an ubuntu 13.10 64 vm to see if `gcc-multilib g++-multilib` are enough.
> Remove ia32-libs-multiarch installation

- lime/utils/AssetLibrary.hx
We use `Assets.getText` after loading via `Assets.loadLibrary`.
This patch makes it work.
> Cache loaded TEXT Assets in AssetLibrary

- lime/text/Font.hx
When the font is already available on the system and happens to be configured as ‘sans-serif’ fallback font, the preloader would never complete...  as the size (offsetWidth) of the font doesn’t actually change.
> Fix (pre)loading of local/system fonts like Arial.

- project/src/ui/FileDialog.cpp
Simply add "*." to the filter (which is the extension of the default filename) and add it as a parameter to the tinyfd function.
Not sure how to properly concatenate wstring so I hope the code is clean.
Didn't do other platforms since I can only test windows atm.
Would be usefull to add to the "open" functions as well.
> Fix for #919 - Add Filter to FileDialog save (Windows only)

- lime/ui/FileDialog.hx
While testing the save functionality I found myself sometimes omitting the extension when saving.
And when I looked back at the saved file, it didn't have any extension, which felt a bit weird. Testing back in flash and in other programs, it does seems to be the general rules of thumb to always saves the file with the "filter" extension if there's one.
> Makes sure extension is used when saving with FileDialog

- dependencies/extension-api/build.gradle
- lime/tools/platforms/AndroidPlatform.hx
- templates/android/template/build.gradle
- templates/extension/dependencies/android/build.gradle
The [Android plugin for Gradle](https://developer.android.com/studio/releases/gradle-plugin.html) uses numbers that look suspiciously similar to Gradle's numbers, but they aren't the same.
I failed to notice the extra period, so my previous pull request (#922) overwrote "`2.1.0`" with "`2.10`," thereby breaking Android builds. This request fixes it and adds an option to change the two values separately.
> Allow setting a different Gradle PLUGIN version.

- lime/_backend/native/NativeGLRenderContext.hx
As discussed [here](https://haxe.org/blog/codingtips-new/), not only is this slightly faster, it lets DCE know it's supposed to keep these constructor functions.
> Improve DCE behavior.

- lime/_backend/native/NativeGLRenderContext.hx
- lime/graphics/opengl/ext/EXT_texture_compression_s3tc.hx
This extension allows DXT1 & DXT5 compressed textures.
Necessary if you want to use compressed textures on Mac & Windows.
> Enable OpenGL s3tc extension

- lime/tools/helpers/IOSHelper.hx
x86_64 can be the default simulator architecture, but i386 is still necessary for older devices.
> Let architecture be specified for simulator builds

- tools/utils/CreateTemplate.hx
This fixes the issue I described [here](https://github.com/openfl/lime/pull/923#issuecomment-280951576), using the first of the two solutions I mentioned. Now extensions will work again without manually editing `build.gradle`!
> Fix 'lime create extension'

- dependencies/extension-api/src/main/java/org/haxe/extension/Extension.java
- templates/android/template/app/src/main/java/org/haxe/lime/GameActivity.java
- templates/extension/dependencies/android/src/main/java/org/haxe/extension/Extension.java
From Android 6.0, if you target sdk with 23 or greater, you need to request the permissions in runtime.
This PR implements the onRequestPermissionsResult in the Extension class. It is required for request in custom extensions.
More info here: https://developer.android.com/training/permissions/requesting.html
> Request Permission result for Android.

- lime/ui/KeyCode.hx
- lime/ui/ScanCode.hx
Implicit conversion between both abstracts is still possible because both have a @:from function
see also https://github.com/HaxeFoundation/haxe/issues/6441
> Remove @:to metadata from conversion functions to support Haxe4

- templates/android/template/app/src/main/AndroidManifest.xml
This PR ensures that status bar will appear when `fullscreen` is set to `false`.
Fixes #938
> Use fullscreen conditional at manifest theme attribute

- lime/tools/helpers/HTML5Helper.hx
As lime supports the google closure compiler to minify assets it would be great to build source map file for this minified JS version as well to have improved debugging experiences in the production version as well. (only if -source-map flag was passed).
> Add possibility to build source map file for minified JS file

- lime/_backend/html5/HTML5HTTPRequest.hx
Check if the method is POST then use request.upload.onprogress otherwise use default request.onprogress
Previously when uploading data via URLLoader in openfl the progress was fired once with value of 200
> Add upload progress event for HTML5HTTPRequest

- lime/_backend/native/NativeHTTPRequest.hx
- lime/net/HTTPRequest.hx
I think this is a really nice memory improvement, otherwise while downloading a 3MB file I can see memory jump to 30MB, using the content-length as the initial buffer size make sure we're not over allocating.
> Use content-length as initial buffer size for HTTPRequest

- lime/project/ProjectXMLParser.hx
- lime/tools/helpers/ModuleHelper.hx
- lime/tools/helpers/StringHelper.hx
Moves module processing into ModuleHelper so it can be accessed from places other than ProjectXMLParser, such as a Project.hxp file.
> Ability to define build modules from project.hxp

- project/src/graphics/opengl/OpenGL.h
Raspberry Pi Needs GLES2 instead of GLES3
> FIXED Raspberry Pi Needing GLES2 instead of GLES3

- lime/tools/helpers/AndroidHelper.hx
Gradle task names can't include spaces, so if there's a space in `ANDROID_GRADLE_TASK`, it must mean that the user wanted to pass extra arguments to Gradle. Currently when they try to pass arguments, they get [this error](http://community.openfl.org/t/issues-building-with-native-text-on-android/9645/3?u=player_03).
> Split ANDROID_GRADLE_TASK based on spaces

- lime/tools/helpers/AIRHelper.hx
For ADL, ANE files need to be extracted to directories. This change will check for an "adl" directory to be created inside extension directory, where the ANE files can be extracted.
The difference of "-extdir" for ADT and ADL is described here: https://help.adobe.com/en_US/air/build/WSfffb011ac560372f-6fa6d7e0128cca93d31-8000.html
>  added ANE support for AIR Debug Launcher (ADL)

- templates/android/template/app/build.gradle
These changes address the wishlist item here: https://trello.com/c/6W5G8ovz/62-would-be-nice-to-prompt-for-password-if-doing-an-android-release-build-and-the-password-is-not-defined
The changes use the technique described here: https://www.timroes.de/2014/01/19/using-password-prompts-with-gradle-build-files/
The changes add a prompt for a password at the console during an android build when the project.xml certificate element does not have a keystore password specified, and another prompt for an alias password if a keystore alias password is not specified. If build.gradle is run from somewhere other than the console, a small dialog pops up asking for the appropriate passwords. This only happens on release builds when the certificate element specifies a keystore file.
> Add prompt for keystore password on android

- lime/net/HTTPRequest.hx
The define 'lime-default-timeout' needs converting to an Int from a string to work.
> Fix to convert 'lime-default-timeout' to int from String

- lime/project/ProjectXMLParser.hx
on AIR, to map different certificates for android and ios, need to copy android and ios targetFlags into defines:
```
<certificate path="Assets/certificate.p12" password="test" if="android" />
<certificate path="Assets/ios_development.p12" password="test" if="ios debug" />
<certificate path="Assets/ios_distribution.p12" password="test" if="ios release" />
```
> for AIR set android and ios targetFlags into defines

- lime/tools/helpers/AIRHelper.hx
- ignore errors when running uninstallApp (we don't want to exit if the app is not already installed)
- check which simulator app path to use
> fixes for testing AIR iphone simulator

- tools/CommandLineTools.hx
Haxe no longer abuses stderr and outputs to stdout, see HaxeFoundation/haxe@f6da2aa. Without this fix, this leads the the following compiler error:
>Error: Lime 5.8.2 is not compatible with Haxe 1 (version 3.2.0 or higher is required)
The fix is basically the same approach vshaxe takes for backwards compatibility: vshaxe/haxe-languageserver@e119a7e
> Fix compatibility with latest Haxe dev

- lime/tools/helpers/IOSHelper.hx
- lime/tools/helpers/TVOSHelper.hx
- lime/tools/platforms/IOSPlatform.hx
- lime/tools/platforms/TVOSPlatform.hx
- templates/ios/template/{{app.file}}/exportOptions-adhoc.plist
- templates/ios/template/{{app.file}}/exportOptions-appstore.plist
- templates/ios/template/{{app.file}}/exportOptions-development.plist
- templates/ios/template/{{app.file}}/exportOptions-enterprise.plist
- templates/tvos/PROJ/exportOptions-adhoc.plist
- templates/tvos/PROJ/exportOptions-appstore.plist
- templates/tvos/PROJ/exportOptions-development.plist
- templates/tvos/PROJ/exportOptions-enterprise.plist
iOS and tvOS `build` generate an `xcarchive` instead of a `.app` when `-archive` is set.
iOS and tvOS `deploy` generates an IPA provisioned for appstore, adhoc, enterprise, or development based on which of those flags is set. Defaults to appstore.
ex: `lime deploy ios -adhoc`
Includes exportOptions-{method}.plist templates for all 4 deployment methods.
> iOS, tvOS IPA generation via deploy command

- lime/graphics/Image.hx
- lime/graphics/utils/ImageCanvasUtil.hx
I did some tests regarding copyPixels and except for very small images (around 10x10 pixels) it is significantly faster to use the canvas implementation instead of manipulating individual pixels via javascript.
E.g. in this benchmark BitmapDataScene it his around 20 times faster to use canvas than data:
https://github.com/innogames/openfl-mark
> Use canvas for copyPixel operations

- lime/utils/DataPointer.hx
**Intention**: fix bug 'Uncaught RangeError: Invalid typed array length: 512'
**Reproduce steps**: 
- checkout standard example of away3d for Haxe https://github.com/openfl/away3d-samples/tree/master/intermediate/PolarBearAWDAnimation
- compile with openfl for HTML5 target and run
- observe the error
**Explanation**: (DataPointer.hx -> toFloat32Array) it happens when param 'length' is bigger then actual 'byteLength' of bufferView (in this specific example length == 2048, but the actual byteLength == 1936), so this is attempt to read more bytes than exist.
> Bugfix Uncaught RangeError: Invalid typed array length: 512

- lime/utils/PackedAssetLibrary.hx
PackedAssetLibrary fixes:
1. respect `rootPath` when loading .pak files
2. `@:keep` to survive `-dce full`
> PackedAssetLibrary fixes

- lime/tools/helpers/IOSHelper.hx
- lime/tools/helpers/TVOSHelper.hx
Only available when using XCode 9 or above.
Can be disabled by setting config.ios.allowProvisioningUpdates and config.ios.allowProvisioningDeviceRegistration to false.
xcodebuild --help for -allowProvisioningUpdates and -allowProvisioningDeviceRegistration:
-allowProvisioningUpdates: Allow xcodebuild to communicate with the Apple Developer website. For automatically signed targets, xcodebuild will create and update profiles, app IDs, and certificates. For manually signed targets, xcodebuild will download missing or updated provisioning profiles. Requires a developer account to have been added in Xcode's Accounts preference pane.
-allowProvisioningDeviceRegistration: Allow xcodebuild to register your destination device on the developer portal if necessary. This flag only takes effect if …
> Automatic iOS and tvOS provisioning and device registration

- lime/_backend/html5/HTML5AudioSource.hx
- lime/media/AudioBuffer.hx
2 sound-related improvements:
1. mp3 detection failed for some of my mp3s. I used the test from [is-mp3](https://github.com/hemanth/is-mp3/blob/master/index.js) which allows one more byte combination than `AudioBuffer._getCodec` did.
2. Playback of dynamically created Sounds (via `loadCompressedDataFromByteArray`) was not working for me in html5. After some debugging I found that Howler did not like calling `volume (value, id)` with `id == -1`. This seems useless anyway, so I disabled it and now playback works fine.
> Sound improvements

- lime/graphics/utils/ImageDataUtil.hx
The previous code went beyond the array bounds. I've just fixed the crash and the blur works good for me but it seems that something weird in the code:
```haxe
var i:Int = 0;
var a:Int;
if (offset < 0) {
while (i < imgA.length) {
a = Std.int(imgB[ i + 3 ] * strength );
a = a < 0 ? 0 : (a > 255 ? 255 : a);
imgB[ i ] = fromPreMult( imgB[ i ], a );
imgB[ i + 1 ] = fromPreMult( imgB[ i + 1 ], a );
imgB[ i + 2 ] = fromPreMult( imgB[ i + 2 ], a );
imgB[ i + 3 ] = a;
i += 4;
}
for (i in imgA.length - offset...imgA.length)
imgB[ i ] = 0;
} else {
i = imgA.length - 4;
while (i >= 0) {
a = Std.int(imgB[ i + 3 ] * strength );
a = a < 0 ? 0 : (a > 255 ? 255 : a);
imgB[ i ] = fromPreMult( imgB[ i ], a );
imgB[ i + 1 ] = fromPreMult( imgB[ i + 1 ], a );
imgB[ i + 2 ] = fromPreMult( imgB[ i + 2 ], a ); …
```
> Fix ImageDataUtil.gaussianBlur crash on iOS

- lime/tools/platforms/EmscriptenPlatform.hx
The way it was written, `lime build emscripten` would fail even if EMSCRIPTEN_SDK was set.
> Fixed detection of EMSCRIPTEN_SDK environment variable

- lime/text/Font.hx
- lime/tools/platforms/HTML5Platform.hx
- lime/utils/AssetLibrary.hx
- templates/haxe/ManifestResources.hx
The lack of font metrics in html5 is reponsible for at least two serious issues (openfl/openfl#908, openfl/openfl#1801). Unfortunately, there doesn't seem to be a reliable method to get font metrics in html5, especially if we want to support webfonts of any format added dynamically at runtime outside our control.
This PR mitigates this issue by:
1. making font metrics automatically available for fonts known at build time
2. allowing the developer to manually add font metrics for dynamically embedded fonts
In both cases, font metrics are used to solve both openfl/openfl#908, openfl/openfl#1801. If not available, the bahaviour stays the same as before. The changes also make it simple to add automated font metric computation in the future, if some reliable method is found.
Detailed summary …
> Font metrics in html5

- lime/tools/helpers/HTML5Helper.hx
Some closure-related fixes/improvements:
1. pass `--strict_mode_input false`, closes openfl/openfl#1827
2. pass `--source_map_location_mapping "/|file:///"`, which causes paths to be prefixed by `file://` (similarly to the haxe-generated .js.map) so that the debugger can find them.
3. Even when closure creates a .js.map, it does _not_ add a `//# sourceMappingURL` to the .js file! We do it ourselves so that the debugger can find it.
4. Haxe can generate source maps for `-final` builds using `-Djs-souce.map`, but minification discards them cause it is triggered by `debug || source-map`. I changed the condition to `<souce.js.map exists> || source-map` which is simpler.
With the above changes debugging a minified app in chrome dev tools works pretty well.
> Minification fixes/improvements

- lime/tools/helpers/FileHelper.hx
- lime/tools/helpers/HTML5Helper.hx
- lime/tools/helpers/ModuleHelper.hx
- lime/tools/helpers/ProcessHelper.hx
- lime/tools/platforms/HTML5Platform.hx
Closure compiler fails with "Sourcemap url was invalid" when publishing to html5.
This fix manually applies the url encoding to the sourceMappingURL at the end of the Haxe-generated .js file if needed.
> Closure fix

- lime/graphics/Image.hx
Fixes #1164
The generated ES6 Image module had this in the Image.__fromBase64() static function:
var image = new Image()
which would instantiate a new object of type lime.graphics.Image as opposed to the intended HTML Image type.
> Fixed the "image.addEventListener is not a function" browser error

- lime/tools/helpers/IOSHelper.hx
Avoids re-generating an xcarchive for each IPA type you wish to create so all IPAs have the same UUID and can be symbolicated with the same symbols.
Usage: `openfl deploy ios [-adhoc] [-appstore] [-enterprise] [-development]`
> Export multiple IPA types with one deploy command

- lime/utils/AssetCache.hx
This fixes compilation server issues we had, because in our code base, `AssetCache` somehow ends up being used in the macro context, and the `AssetsMacro.cacheVersion` call becomes a macro-in-macro call that messes up the whole compilation server cache and ultimately fails to compile with an `Invalid call` error.
> don't call AssetsMacro.cacheVersion from AssetCache within the macro context

- project/src/graphics/opengl/OpenGLBindings.cpp
For compiling on the raspberry pi, 
OpenGLBindings needs to include 
` && !defined (RASPBERRYPI)`
in 3 places.
> FIX conditionals in openglbindings to include 'defined (RASPBERRYPI)'

- project/src/graphics/opengl/OpenGLBindings.cpp
> FIX, typo in conditionals RASPBERRYPI in openglbindings

- project/Build.xml
updates RaspberryPi  (rpi) GLES and EGL linkerflags to point to the brcmGLESv2 and brcmEGL libraries. These are available on both an up to date Raspbian Jessie and the newer Raspbian Stretch.
> update Rpi GLES and EGL linkerflags

- lime/utils/ObjectPool.hx
Fixed crash if `lime.utils.ObjectPool` is initialized with create, clean and size params.
> Fix crash on lime.utils.ObjectPool if size is set #1184

- lime/tools/platforms/AndroidPlatform.hx
According to Android's NDK guide, the folder should have an armeabi-v7a directory instead of armeabi-v7 ( https://developer.android.com/ndk/guides/abis.html#sa  )
I still kept the default behaviour (a single armeabi folder) if the target is arm-v7 only for compatibility, since androids older than 4.0.4 still use that folder (https://developer.android.com/ndk/guides/abis.html#am , first note).
For the future, Lime should remove armeabi's folder entirely (since this is deprecated in NDK R16).
> Change armeabi-v7 folder to armeabi-v7a

- CHANGELOG.md
- lime/_backend/html5/HTML5Window.hx
Currently mouse events are added to a div element and therefore releasing mouse outside of the browser window doesn't trigger mouseup event. A mouse up event listener is added to the window and it is only executed when mouse is released outside of the window. This way we catch the "RELEASE_OUTSIDE" event
> MouseUp event added on the window a RELEASE_OUTSIDE event can be detected.

- project/src/backend/sdl/SDLSystem.cpp
Attempting to convert a null pointer to std::string seems to be undefined behavior, see https://stackoverflow.com/questions/5867242/how-to-put-the-contents-of-getenv-into-a-string. In my case it was causing a crash.
> Guard against getEnv("HOME") returning null on some platforms

- project/src/graphics/opengl/OpenGLBindings.cpp
RaspberryPi is Linux but gl_debug  is not avaible. 
Adding a conditional (3x) for RASPBERRYPI in openglbindings.cpp
> add RASPBERRYPI conditional in openglbindings

- lime/graphics/utils/ImageDataUtil.hx
This modification helped me to reduce memory consumption on html5 target (especially with activated `openfl_power_of_two` haxedef).
I'm not sure if it's right to do so, and ask you to consider this change
> Update ImageDataUtil's resizeBuffer method so it clears source data

- lime/graphics/Image.hx
We want to access normal source value which can be HTML Image element, also suitable for texture uploading.
If anyone needs a canvas, they can convert explicitly (as it's actually done already).
> Don't do any magical implicit to-canvas conversion in the Image.src getter.

- project/src/ExternalInterface.cpp
- project/src/backend/sdl/SDLSystem.cpp
Rewritten https://github.com/openfl/lime/pull/1207 against latest commit in lime:develop.
Change SDLSystem::fopen() on Windows to interpret filename as a UTF-8 string and call ::_wfopen() instead of ::fopen(). Fix conversions between UTF-8 strings and UTF-16 wstrings. These changes allow Lime to open files (e.g. assets and .sol files) from paths which use extended Unicode characters, e.g. user folders where the Windows username includes accents.
This commit resolves issues #1083 and #1016.
I suspect the FT_New_Face() code path in src/text/Font.cpp may still have problems, as it relies on FreeType to load the file, and FreeType appears to just use fopen() (in FT_Stream_Open()). However, I've tried the PiratePig sample and it seems to load its font asset just fine - so it's presumably using …
> Fix Unicode file path support on Windows

- src/lime/system/System.hx
With newest Lime (6.4.0) we were getting some build errors on Windows and iOS. It's probably due to some library that called a Lime system function in a macro when it shouldn't, possibly via OpenFL. Nonetheless Lime can protect against this. I believe this PR will resolve the issues.
Example errors:
```
- Running command: haxe Export/windows/cpp/final/haxe/final.hxml -D no_console
C:/cygwin64/opt/haxe/lib/lime/6,4,0/lime/system/System.hx:713: characters 19-58 : Class<lime._backend.native.NativeCFFI> has no field lime_system_get_device_model
C:/cygwin64/opt/haxe/lib/lime/6,4,0/lime/system/System.hx:744: characters 20-60 : Class<lime._backend.native.NativeCFFI> has no field lime_system_get_device_vendor
C:/cygwin64/opt/haxe/lib/lime/6,4,0/lime/system/System.hx:841: characters 22-63 : …
```
> Fix Windows and iOS compile CFFI issues

- src/lime/_internal/macros/CFFIMacro.hx
`return null` is no longer allowed for Void-returns: HaxeFoundation/haxe#7198
This was causing issues when building a completion cache with the HL target:
lime/src/lime/_internal/backend/native/NativeCFFI.hx:3435: characters 9-82 : Cannot return `null` from Void-function
> Fix CFFIMacro for latest Haxe dev

- src/lime/media/AudioBuffer.hx
Looks like MP3 could have FF FX bits (https://www.garykessler.net/library/file_sigs.html),
but in my sample for mp3 22k second bit was 243 and after change normally plays in Firefox and Chrome.
Need test and maybe update algo to take into account all second bits started with F
> Html5 mp3 detection update

- src/lime/media/HTML5AudioContext.hx
A number of functions are annotated as `: Void` but return the result of call. In recent versions of the HTMLMediaElement specification `play()` [returns a promise](https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/play#Return_value). To avoid errors when the externs are updated I've removed the `return`.
(See https://github.com/HaxeFoundation/haxe/pull/7354)
> HTML5 externs fix: void functions may return non-void

- src/lime/tools/HXProject.hx
- src/lime/tools/ProjectXMLParser.hx
Allow a window title to be set as an attribute on a window element in project.xml
Defaults back to Meta.title when the attribute is not set.
> window title can be set as an attribute in project.xml

- src/haxe/io/Bytes.hx
Adds `#if (haxe_ver < 4.0)` around a reference to `js.html.compat`
See https://github.com/HaxeFoundation/haxe/issues/7091
> js.html.compat is being removed in haxe 4

- src/lime/text/UTF8String.hx
If the String isn't a valid UTF8 string haxe.Utf8.length() will throw a cryptic "Invalid UTF8" error while Unifill.uLength() will return 0
> Use Unifill.uLength() in UTF8String get_length()

- src/lime/_internal/macros/AssetsMacro.hx
AssetsMacro.cacheVersion was changed in this commit.
https://github.com/openfl/lime/commit/aa4c4b6a05a31d0b70c409682e889b59c35cadc3
And now, it is calculated at run time.
However, I think compile time calculation is better than run time one, because of browser cache in html5.
> calculate AssetsMacro.cacheVersion at compile time

- src/lime/_internal/backend/html5/HTML5HTTPRequest.hx
Compiling with -DforceLocal allow files to be served locally when browser supports this.
Use case : Cordova use a webview and many files can't be loaded without allowing http status 0 as successful. So this PR allows apps made with openfl to run on Cordova.
> Add forceLocal define to allow loading locally

- src/lime/text/UTF8String.hx
Turns out that having a map of upper to lower case unicode glyphs, even taking into account asymmetrical operations, isn't enough. A good example of this is Turkish.
Turkish uses what looks pretty much just like some letters from the Latin alphabet with a few variants with diacritics. 
https://unicode-table.com/en/alphabets/turkish/
And indeed, these are all just using the same glyphs as the various european alphabets do. Same exact unicode points. BUT, the rules for Turkish are subtly different.
Notably, Turkish has dotted and undotted i's, in both lower and upper case.
Capital I: https://unicode-table.com/en/0049/
Small dotless I: https://unicode-table.com/en/0131/
Capital dotted I: https://unicode-table.com/en/0130/
Small dotless I: https://unicode-table.com/en/0069/
The tricky bit is, …
> add language-specific rules (for e.g. Turkish) to Utf8String casing

- templates/electron/haxe/ElectronSetup.hx
- templates/electron/hxml/debug.hxml
- templates/electron/hxml/final.hxml
- templates/electron/hxml/release.hxml
Added 'suppress_devtools' compiler flag to prevent auto-opening of dev tools when targeting Electron.
> Added 'suppress_devtools' compiler flag

- templates/electron/haxe/ElectronSetup.hx
--autoplay-policy, no-user-gesture-required flags to allow video and audio to play without user input within electron
> video and audio auto play

- src/lime/_internal/graphics/ImageDataUtil.hx
This actually broke DropShadow and thus have to be reverted. My sample code:
```haxe
package;
import openfl.display.Sprite;
import openfl.filters.BlurFilter;
import openfl.filters.DropShadowFilter;
import openfl.text.TextFormat;
import openfl.filters.GlowFilter;
import openfl.text.TextField;
class Main extends Sprite {
private var text_field_1(null, null):TextField;
private var text_field_2(null, null):TextField;
private var text_field_3(null, null):TextField;
public function new() {
super();
var blur:BlurFilter = new BlurFilter(4.0, 4.0);
var glow:GlowFilter = new GlowFilter(0x00FF00);
var shadow:DropShadowFilter = new DropShadowFilter(4, 45, 0xFF0000, 1.0, 0.0, 0.0);
var format:TextFormat = new TextFormat('Arial', 40);
this.addChild(this.text_field_1 = new TextField()); …
```
> Reverted changes with strength in Gaussian Blur

- templates/electron/haxe/ElectronSetup.hx
`electron.main.App.commandLine` is now defined in electron externs, no need for untyped workaround anymore.
> Use electron.main.App.commandLine type

- src/lime/_internal/graphics/ImageDataUtil.hx
Otherwise Glow strength is not taken into account. Tested on our soon-to-be-released app.
> Switched return values in gaussianBlur

- src/lime/_internal/backend/html5/HTML5Window.hx
Checks whether the right click mouse up or down event was cancelled to prevent to context menu from showing up on html5. coincides with an [OpenFL PR](https://github.com/openfl/openfl/pull/2097) where down events are cancelled. 
It's possible we only need to check down events and the mouseup cancels mean nothing, but I left them in in case it's needed for other OS/browser context menus.
> check mousedown cancelled for context menu disabling

- templates/electron/template/package.json
NPM package.json name property can't have non-URL safe characters, so it's more suited to using the 'packageName' than the 'title'.
This also helps when using tools like electron-packager, which use the package name as a folder name.
Spec:
https://docs.npmjs.com/files/package.json
> Change NPM package.json 'name' property to use 'packageName' instead of 'title' 

- src/lime/net/HTTPRequest.hx
- templates/haxe/ManifestResources.hx
The `#if display private #end` trick doesn't work with Haxe 4 because during "indexing" / creation of the parser cache, `display` is not defined (because the results have to be usable for compilation too). So currently the `__ASSET__` classes show up in completion:
`@:noCompletion` fixes that.
I also found some types in `HTTPRequest` prefixed with underscores that don't look like they should show up?
> Hide __ASSET__ classes with @:noCompletion

- project/src/graphics/utils/ImageDataUtil.cpp
- src/lime/_internal/graphics/ImageDataUtil.hx
Fixes [this issue](https://github.com/openfl/openfl/issues/2127), which I erroneously opened as an openfl issue.
This fixes the issue on HTML and Neko targets. I am unable to test on C++ target, but I presume the issue occurred there, and that it fixes the issue there too.
> Remove offset from AlphaView in CopyPixels 

- src/lime/ui/Haptic.hx
Haptic support for HTML5 via Navigator.vibrate (https://developer.mozilla.org/en-US/docs/Web/API/Vibration_API)
---
**note:**
w3c spec says to vibrate on even elements of the pattern and android waits on even elements.
**w3c**
> If the index of time is even (the first entry has index 0), vibrate the device for time milliseconds.
https://w3c.github.io/vibration/
**android**
> The first value indicates the number of milliseconds to wait before turning the vibrator on. 
https://developer.android.com/reference/android/os/Vibrator.html#vibrate(long[],%20int)
The code has a line that adds a zero to the pattern to make the html5 behavior match the android behavior.
> Haptic support on HTML5

- src/lime/_internal/graphics/ImageCanvasUtil.hx
This PR removes the line that forces `imageSmoothingEnabled` to false.
It fixes [openf#2102](https://github.com/openfl/openfl/issues/2102), and potentialy #1116 and [this one](https://community.openfl.org/t/bitmapdata-draw-smoothing-does-not-work-html5/7509) too. 
If it is intended that the smoothing is disabled here, you can close this PR and I'll make another one in OpenFL to adjust `BitmapData.draw` accordingly.
> Fix canvas smoothing on html5

- project/Build.xml
- templates/winrt/static/Main.cpp
DisplayingABitmap works when compiling with
lime rebuild winrt -static -Dcairo -debug -m64
openfl test project.xml winrt -static -Dcairo -debug
And adding a Sys.sleep(1); in openfl/assets/templates/haxe/ApplicationMain.hx, before var result = app.exec ();
> Enable cairo for winrt

- src/lime/graphics/opengl/ext/ANGLE_instanced_arrays.hx
- src/lime/graphics/opengl/ext/EXT_blend_minmax.hx
- src/lime/graphics/opengl/ext/EXT_color_buffer_float.hx
- src/lime/graphics/opengl/ext/EXT_color_buffer_half_float.hx
- src/lime/graphics/opengl/ext/EXT_disjoint_timer_query.hx
- src/lime/graphics/opengl/ext/EXT_frag_depth.hx
- src/lime/graphics/opengl/ext/EXT_sRGB.hx
- src/lime/graphics/opengl/ext/EXT_shader_texture_lod.hx
- src/lime/graphics/opengl/ext/EXT_texture_filter_anisotropic.hx
- src/lime/graphics/opengl/ext/OES_element_index_uint.hx
- src/lime/graphics/opengl/ext/OES_standard_derivatives.hx
- src/lime/graphics/opengl/ext/OES_texture_float.hx
- src/lime/graphics/opengl/ext/OES_texture_float_linear.hx
- src/lime/graphics/opengl/ext/OES_texture_half_float.hx
- src/lime/graphics/opengl/ext/OES_texture_half_float_linear.hx
- src/lime/graphics/opengl/ext/OES_vertex_array_object.hx
- src/lime/graphics/opengl/ext/WEBGL_color_buffer_float.hx
- src/lime/graphics/opengl/ext/WEBGL_compressed_texture_atc.hx
- src/lime/graphics/opengl/ext/WEBGL_compressed_texture_etc.hx
- src/lime/graphics/opengl/ext/WEBGL_compressed_texture_etc1.hx
- src/lime/graphics/opengl/ext/WEBGL_compressed_texture_pvrtc.hx
- src/lime/graphics/opengl/ext/WEBGL_compressed_texture_s3tc.hx
- src/lime/graphics/opengl/ext/WEBGL_debug_renderer_info.hx
- src/lime/graphics/opengl/ext/WEBGL_debug_shaders.hx
- src/lime/graphics/opengl/ext/WEBGL_depth_texture.hx
- src/lime/graphics/opengl/ext/WEBGL_draw_buffers.hx
- src/lime/graphics/opengl/ext/WEBGL_lose_context.hx
`extern @:noCompletion ...`
to 
`@:noCompletion extern ...`
> Fix syntax error in extensions on the html5 target

- src/lime/media/AudioBuffer.hx
Added a compilation flag `force_html5_audio` to force howler to always use html5 audio.
I don't think anyone will find this useful but it shouldn't do any harm to have.
> Added the flag "force_html5_audio" for howler

- tools/platforms/WindowsPlatform.hx
Get the Windows SDK bin directory automatically from the latest sdk installed version, when making an -appx
> [winrt] Fix retrieve bin directory for latest Windows 10 SDKs

- src/lime/app/Application.hx
In the block documentation for Application.createWindow, changed
the legacy window parameter to the current attributes parameter
> Updated the documentation for createWindow

- templates/html5/output.js
Here's an attempt to solve the AMD issue (#1328).
If the app is loaded via AMD we do the following:
- `$hx_exports` is a fresh object, so `lime` is not exported globally, and each app gets a 100% fresh scope. `@:expose`d stuff are completely independent for each app, they can be neatly accessed via the result of `lime.embed`!
- We call `define()` to register the code.
- We disable AMD while the embeded libraries are loading, otherwise they are going to call define, which won't work.
So in the end we can do:
```
require(['myapp'], function(lime) {
lime.embed(...);
});
```
- PS1. Embedded libraries are still registered globally, which is not ideal (theoretically a conflict between different pako versions could happen) but not a major issue. Ideally, we could use a commonjs emulator (a la …
> Add AMD/requirejs compatibility

- src/lime/tools/HTML5Helper.hx
The already-minified embedded libaries are currently being re-minified. They contain code that looks suspicious if written by a human, like
```
while(--g);
```
So closure complains:
```
WARNING - If this if/for/while really shouldn't have a body, use {}
```
This is most-likely harmless, so until the pipeline is improved, it makes sense to just disable the warnings.
> Disable closure warnings for 'suspicious' code

- templates/haxe/ManifestResources.hx
This is broken since a2794c9deae2bd7e1ea013d979504221fbc35bb1
> Fix asset loading on Windows

- src/lime/utils/DataView.hx
- src/lime/utils/Float32Array.hx
- src/lime/utils/Float64Array.hx
- src/lime/utils/Int16Array.hx
- src/lime/utils/Int32Array.hx
- src/lime/utils/Int8Array.hx
- src/lime/utils/UInt16Array.hx
- src/lime/utils/UInt32Array.hx
- src/lime/utils/UInt8Array.hx
- src/lime/utils/UInt8ClampedArray.hx
This is needed to compile with HaxeFoundation/haxe#8422 because abstract implicit casts are not transitive.
> Fix HTML5 compilation with latest Haxe dev

- src/lime/_internal/backend/html5/HTML5Window.hx
ApplicationMain template always has antialiasing parameter, so it is needed to be ckecked for value
> Fix HTML5Window antialiasing check

- src/lime/_internal/backend/native/NativeHTTPRequest.hx
- src/lime/net/curl/CURL.hx
OpenFLs Urlloader fails to respond with anything when target is Hashlink and the request  protocol is http/https. From what i can tell when debugging the issue seems to be related to the signature for the `WRITEFUNCTION` callback function passed to the native curl method, for some reason when targeting HL the second parameter is unavailable. 
Side note: 
Lime should probably use XFERINFOFUNCTION instead of PROGRESSFUNCTION 
https://curl.haxx.se/libcurl/c/CURLOPT_PROGRESSFUNCTION.html
> Tweaks to make HTTP requests work with HashLink

- templates/electron/hxml/debug.hxml
- templates/electron/hxml/final.hxml
- templates/electron/hxml/release.hxml
That sets the 'nodejs' compiler flag, which emits improper JavaScript when executing in the Electron window.
> Don't use the hxelectron library when building ApplicationMain.

- src/lime/_internal/backend/html5/HTML5Window.hx
This option is also [used in pixi.js](https://github.com/pixijs/pixi.js/blob/824b8d20ecbacad0c80d82a002009aded7f62ab1/packages/utils/src/browser/isWebGLSupported.js#L16) do detect is WebGL is supported
See https://www.khronos.org/registry/webgl/specs/latest/1.0/#5.2.1 for description:
If the value is true, context creation will fail if the implementation determines that the performance of the created WebGL context would be dramatically lower than that of a native application making equivalent OpenGL calls. This could happen for a number of reasons, including:
* An implementation might switch to a software rasterizer if the user's GPU driver is known to be unstable.
* An implementation might require reading back the framebuffer from GPU memory to system memory before compositing it with …
> Add `failIfMajorPerformanceCaveat` option

- dependencies/extension-api/build.gradle
- templates/android/template/app/build.gradle
- templates/android/template/build.gradle
- templates/extension/dependencies/android/build.gradle
- tools/platforms/AndroidPlatform.hx
This pull request will update to the gradle 5.6.3 and gradle android plugin 3.5.1 ( as default) .
Also there some fix for  ANDROID_GRADLE_TASK .
From gradle 4.x each apk file is in separate folder ( debug/ , release/ , etc) , so this is also fixed .
In build.gradle "compile" is not supported anymore, so it was replaced with api ( or implementation)
> Update to the latest Gradle 5.6.3 and Gradle Android plugin 3.5.1

- src/lime/tools/HXProject.hx
- src/lime/tools/ImageHelper.hx
- src/lime/tools/LaunchStoryboard.hx
- src/lime/tools/ProjectXMLParser.hx
- templates/ios/storyboards/splash.storyboard
- templates/ios/template/{{app.file}}.xcodeproj/project.pbxproj
- templates/ios/template/{{app.file}}/{{app.file}}-Info.plist
- tools/platforms/IOSPlatform.hx
Apple seems to be pushing more and more to stop the use of static launch images. As far as I can tell, it's not even possible to target the 11-inch iPad with a static launch image, like it has been for previous iDevices.
If a launch storyboard is used, static launch images will be ignored. The storyboard has to be set up in xcode, but perhaps some simple templates can be included in lime.
> Allow use of launch storyboard instead of launch images on iOS

- dependencies/extension-api/build.gradle
- templates/android/template/build.gradle
- templates/android/template/gradle/wrapper/gradle-wrapper.properties
- templates/extension/dependencies/android/build.gradle
- Use [gradle's built-in repository notations](https://docs.gradle.org/current/userguide/declaring_repositories.html) for jcenter & google.
- Use https for `distributonUrl` in gradle-wrapper.properties as `services.gradle.org/distributions/` is only accessible over https.
> Android gradle-related files update (http->https)

- src/lime/_internal/backend/native/NativeOpenGLRenderContext.hx
This fixes a crash in Neko, where getParameter returned an int, which caused a crash in __getObjectID
> Add case for RenderBufferBinding to getParameter

- src/lime/tools/XCodeHelper.hx
Iphone 6 silmulator is no longer supported, updated to iphone 11
Fixes https://github.com/haxelime/lime/issues/1355
> Update default iphone simulator

- src/lime/utils/Float32Array.hx
- src/lime/utils/Float64Array.hx
- src/lime/utils/Int16Array.hx
- src/lime/utils/Int32Array.hx
- src/lime/utils/Int8Array.hx
- src/lime/utils/UInt16Array.hx
- src/lime/utils/UInt32Array.hx
- src/lime/utils/UInt8Array.hx
- src/lime/utils/UInt8ClampedArray.hx
This fixes a few compilation errors with some from/to casts with Haxe 4. I was getting the following error when building html5:
`You can only declare from/to with compatible types`
For some reason, using `@:to` instead of `abstract T (_) to` do the trick :)
> Fix compilation error with js array buffers (haxe 4)

- README.md
...at least I'm assuming that it's outdated, since this seems to have made it to the readme on Haxelib, which can be rather confusing for users:
https://lib.haxe.org/p/lime/
> Remove outdated line from readme

- project/src/system/JNI.cpp
This PR fixes an off by one in `strncmp(src,"org/haxe/lime/HaxeObject;", 24)` call. The string literal `"org/haxe/lime/HaxeObject;"` has a length of 25 and so the current implementation would also match e.g. `"org/haxe/lime/HaxeObjectSOMETHING;"` strings.
> Fix off by one when finding HaxeObject; JNI string

- tools/platforms/IOSPlatform.hx
- tools/platforms/TVOSPlatform.hx
Xcode's xcframework dependencies are used by the latest versions of the Google AdMob SDK. They appear in the .pbxproj file in exactly the same way as frameworks, so the framework code is simply copied and modified as needed.
> Allow xcframework dependencies for Xcode.

- project/Build.xml
This file no longer exists in hxcpp. `lime rebuild ios` works correctly without the removed line.
> fix rebuild iOS due to bad Zlib.cpp path

- tools/CommandLineTools.hx
> Fix for lime build won't read .build if git is present

- src/lime/app/Event.hx
quick method to remove all listeners from a lime event
> [feature] add removeAll feature for lime event

- src/lime/_internal/backend/html5/HTML5HTTPRequest.hx
- src/lime/_internal/backend/html5/HTML5Window.hx
- src/lime/graphics/ImageBuffer.hx
- src/lime/system/System.hx
- src/lime/tools/AssetHelper.hx
- src/lime/tools/FlashHelper.hx
- src/lime/utils/ArrayBuffer.hx
- src/lime/utils/AssetCache.hx
- tools/CommandLineTools.hx
`Std.is()` has been deprecated in Haxe 4.2: https://github.com/HaxeFoundation/haxe/commit/8ef3be1ae80fe4361572100fe7988518bc59c9ed
Rather than using `Std.isOfType()`, it's cleaner to use the `is` syntax with mandatory parens if possible* - it's already available since Haxe 3.4, so it doesn't require conditional compilation (afaik that's the oldest version still supported by OpenFL anyway).
<sup>*possible whenever the RHS is a type rather than an expression</sup>
> Fix Std.is() deprecation warnings with Haxe 4.2

- templates/android/template/app/src/main/AndroidManifest.xml
This should fix the problem where Android apps would rotate to any direction even though the window orientation  was specified.
and yes it actually says `IOS` in `SDL_ENV.SDL_IOS_ORIENTATIONS` but that's what the  SDL define says.
```
/**
*  \brief  A variable controlling which orientations are allowed on iOS/Android.
*
*  In some circumstances it is necessary to be able to explicitly control
*  which UI orientations are allowed.
*
*  This variable is a space delimited list of the following values:
*    "LandscapeLeft", "LandscapeRight", "Portrait" "PortraitUpsideDown"
*/
#define SDL_HINT_ORIENTATIONS "SDL_IOS_ORIENTATIONS"
```
> Fix for android screen orientation

- src/lime/_internal/backend/html5/HTML5AudioSource.hx
Patches an issue causing audio to play twice if force_html_audio is enabled. This appears to be an oversight with Howl.
> Fix audio stutter on HTML5

- src/lime/_internal/backend/html5/HTML5Window.hx
- src/lime/graphics/RenderContextAttributes.hx
- src/lime/system/System.hx
- src/lime/tools/HXProject.hx
- src/lime/tools/WindowData.hx
- templates/haxe/ApplicationMain.hx
Recent update of Google Chrome has changed behavior of `failIfMajorPerformanceCaveat` option for creation of WebGL context - it fails more frequently for old videocards.
This change add setting for `failIfMajorPerformanceCaveat`, which is `false` by default now, but you could change it with "project.xml" or "project.hx" files by adding attribute `failIfMajorPerformanceCaveat` to the window
> Add failIfMajorPerformanceCaveat setting

- .github/workflows/main.yml
Depending on how the CI server is set up, the task may fail to create the `lime` command. For instance, #1416 returned failure due to dependabot's settings, not due to the contents of the pull request.
This commit provides a simple workaround for those cases, running only if `lime setup -alias` fails. It shouldn't have any effect in cases that already work.
> Fix CI edge case

- include.xml
Lime requires the `Deque` class to target HashLink, which only became available in Haxe 4. If you try, Lime should at least let you know what's wrong.
Helps address #1403.
> Improve the error message for an unsupported use case

- src/lime/ui/FileDialog.hx
see https://community.openfl.org/t/problem-with-filereference-save-xml/12776/2
fix : https://github.com/openfl/openfl/issues/2423
> remove garbage from bytes when saving a file on html5

- tools/CommandLineTools.hx
By setting `<meta build-number=".build" />`, you can force Lime not to calculate a build number from git or svn, but instead use the default option of getting it from the .build file.
Since setting this value would previously have produced useless build numbers, it's unlikely that this affects any existing builds.
This should fix #1409 without causing #1414 to happen again.
> Add flag to read buildNumber from .build.

- src/lime/tools/ProjectHelper.hx
Now that `project.workingDirectory` exists, we may as well use it.
In the future, we might change this line to `if (string == "projectDirectory" || string == "workingDirectory")` because the latter matches the variable name, and it's nice to have consistent naming conventions. For now I decided to make the minimum number of changes.
> Use existing "workingDirectory" value instead of re-calculating.

- src/lime/_internal/backend/native/NativeAudioSource.hx
In order to make  music streaming usable in OpenFL on native targets some tweaks to Lime is necessary.
1. when using stop, expected behavior in OpenFL is to return to the beginning of a track ( the current behavior is more like a pause )  so i have changed this  (see line 312)
2. when the backend runs out of buffer it stops playing (and seems to refuse to continue), this becomes an issue when the main thread is occupied for too long (loading assets, resizing window etc.) so i have added check to see if it was playing before it ran out of buffer and if so, resume playback. (line 296 - 302)
3. Since the buffers are quite small and only 3 by default  any small holdup in the main thread might cause stuttering, i have therefor added an option to set a different amount of buffers when compiling …
> Making NativeAudio buffers configurable &  playback  behaving like other sources.

- src/lime/_internal/backend/native/NativeOpenGLRenderContext.hx
The `lime_gl_get_shader_info_log` function could, sometimes, return null. Also, it seems not yet implemented for the HashLink target, so at the moment it would always return null. 
However, in the hl target we are also forcing a conversion to String that is causing the function to crash when the result is null (see [this issue in OpenFL](https://github.com/openfl/openfl/pull/2473#issuecomment-820727777)).
This PR adds a check if the result is null before attempting the conversion.
> fix: getShaderInfoLog result could be null on HashLink target

- src/lime/tools/AssetHelper.hx
Packed asset libraries are sequences of individual files, sometimes compressed, and concatenated. If each file is compressed, this causes the asset pack as a whole to begin with compressed file headers, which may cause some software to mistake the file as being one large compressed file, which it isn't.
For example, some html5 web portals (in particular, the very popular itch.io) may try to automatically determine if a file is gzip-compressed, and if they are, serve the file with the "content-encoding: gzip" header. That will cause a web browser to decompress the file while downloading it, leading to two issues:
1. The compressed file header is only for the first file in the pack, so we'll only receive the data for the first file.
2. The data will be in an already-decompressed state, …
> Don't let packed asset files begin with a compression header

- src/lime/_internal/backend/native/NativeAudioSource.hx
The sequel to pull #1456, this request fixes two issues brought up in that thread. I would love to have amended that request, but I didn't feel like spending the time to figure out how.
Anyway, the big issue is that sound could potentially play despite `playing` being false. Besides that, one of the comments was incorrect.
> Fix playback behavior in `NativeAudioSource`

- src/lime/graphics/opengl/GLShader.hx
Fixes #1451.
The new code uses both `getShaderInfoLog()` and `getShaderParameter()` to recognize the following states:
- no errors, no warnings: (`shaderInfoLog = null`, `compileStatus = 1`) --> show nothing;
- no errors,  warnings present: (`shaderInfoLog != null`, `compileStatus = 1`) --> show "Info compiling shader..." & infoLog on Log.debug();
- errors present: (`shaderInfoLog != null`, `compileStatus = 0`) --> show "Error compliling shader..." & infoLog on Log.error().
> fix: Shader compiler is giving warnings only when there are errors present

- tools/utils/CreateTemplate.hx
As pointed out in issue #976, `lime create project XYZ` doesn't rely on any project but Lime itself, and shouldn't try to [load lime-samples](https://github.com/haxelime/lime/blob/develop/include.xml#L203). As far as I can tell, setting "create" has no other effect.
> Remove lime-samples dependency in `createProject`.

- templates/extension/.gitignore
No one ever wants to include the intermediate build files. Might as well save them the trouble of making their own .gitignore file.
That said, I've found more than one project that includes the ndlls, so I left those as suggestions.
> Ignore project/obj in extensions.

- project/Build.xml
- tools/platforms/AndroidPlatform.hx
Latest hashlink requires `uchar.h`, which is only included starting from API level 21.
According to Android Studio, 98% of Android devices run API level 21 or higher.
See also #1517.
> Upgrade to android API level 21.

- src/lime/_internal/backend/flash/FlashAudioSource.hx
- src/lime/_internal/backend/html5/HTML5AudioSource.hx
- src/lime/_internal/backend/native/NativeAudioSource.hx
- src/lime/media/AudioSource.hx
Finally got hands dirty and figured out some of the backend stuff to get pitch changing stuff available.
I've tested Windows and HTML5, I'm just assuming most of the NativeBackend stuff works in a generally similar way. 
NOT implemented Flash, I'm assuming it'd give you errors as getPitch() and setPitch() and the FlashAudioBackend aren't implemented. 
I believe this closes #871
> Audio pitch change implementation

- templates/android/template/app/src/main/AndroidManifest.xml
Otherwise it throws the following error on build:
"Apps targeting Android 12 and higher are required to specify an explicit value for `android:exported` when the corresponding component has an intent filter defined. See https://developer.android.com/guide/topics/manifest/activity-element#exported for details."
To publish apps on Google Play everyone needs to target SDK 31+, which is Android 12+, so this is like a must now.
Works fine with older version of SDKs. (I've checked 28.)
If "true", the activity is accessible to any app, and is launchable by its exact class name.
If "false", the activity can be launched only by components of the same application, applications with the same user ID, or privileged system components. This is the default value when there are no intent filters.
> Add `exported="true"` to AndroidManifest.xml

- dependencies/extension-api/src/main/java/org/haxe/lime/HaxeObject.java
- src/lime/_internal/backend/native/NativeApplication.hx
- src/lime/system/ForegroundWorker.hx
- src/lime/system/JNI.hx
Android apps always use at least two threads: the UI thread (where most Java code takes place), and the Haxe thread (where most Haxe code takes place). This often causes thread-related errors when using JNI to send messages between the two types of code.
When sending messages from Haxe to Java, you typically use `Extension.callbackHandler.post()` to run your code on the UI thread, because that thread can safely interact with the Android system.
When sending messages the other way (Java to Haxe), there's no easy equivalent. We could make a `Handler` for the Haxe thread, but it would block Lime from running (or vice versa). You could use `Timer.delay()`, but Lime's custom implementation of `Timer` is not thread-safe. Then there's the function `MainLoop.runInMainThread()`, except it …
> Add thread management tools for Android

- src/lime/_internal/backend/native/NativeHTTPRequest.hx
- src/lime/net/HTTPRequest.hx
Turns out, [`HTTPRequest`'s call](https://github.com/openfl/lime/blob/02617a854d02777ebb0e9534c1d59642938e8aef/src/lime/net/HTTPRequest.hx#L114) is only needed for internet requests. Files on the local machine will be [loaded directly into `bytes`](https://github.com/openfl/lime/blob/02617a854d02777ebb0e9534c1d59642938e8aef/src/lime/_internal/backend/native/NativeHTTPRequest.hx#L427), leaving `buffer` empty. Calling `buildBuffer()` will then delete the data.
> Only call `buildBuffer()` when needed.

- templates/extension/include.xml
I can't think of any practical reasons for an Android extension to compile an ndll. All of Android's system functions require Java, not C++, and you can get the speed of C++ just by writing Haxe code.
I surveyed several Android extensions on lib.haxe.org, and not one of them used ndlls when targeting Android.
> Don't expect Android extensions to use ndlls

- src/lime/tools/Icon.hx
- src/lime/tools/IconHelper.hx
- src/lime/tools/ProjectXMLParser.hx
With this, a library can set a "default" icon, to be used only if the user doesn't provide a better one. Closes #1508.
> Implement `Icon` priorities.

- templates/android/template/app/src/main/AndroidManifest.xml
When the user switches between dark and light themes, Android destroys and recreates the activity. However, Lime activities can't be recreated like this, and just close instead.
Since we don't actually use the system theme, there's no reason for Android to do this. Simplest solution is to suppress it. The only question is, should we expose [`onConfigurationChanged()`](https://developer.android.com/reference/android/app/Activity#onConfigurationChanged\(android.content.res.Configuration\)) to extensions, or is this too niche to be worth it?
References:
https://developer.android.com/guide/topics/resources/runtime-changes
https://developer.android.com/guide/topics/ui/look-and-feel/darktheme#config-changes
Closes #1532.
> Suppress `uiMode` configuration changes.

- src/lime/_internal/backend/native/NativeHTTPRequest.hx
Followup to these two commits:
02617a854d02777ebb0e9534c1d59642938e8aef
ad3a632927c06e5ed7d4b14ca3a6dd95a2e6c720
In the second commit, the `buildBuffer` call in `HTTPRequest` was found to conflict with the way local requests are made, with the bytes being set directly. So `buildBuffer` was moved to `NativeHTTPRequest` instead. Upon promise completion, now, the value of bytes should always be correct, and `buildBuffer` need not be called.
But `buildBuffer` is called again in `NativeHTTPRequest.loadText`. For local requests, this will lead to the same problem that the second commit fixed (presumably), and for network requests, this leads to the nulled out buffer being accessed a second time, resulting in a crash.
So since the received value of bytes is already correct and `buildBuffer` is …
> Fix NativeHTTPRequest.loadText

- src/lime/ui/FileDialog.hx
A while ago i made a pull request that fixed pretty much the same error, but i only fixed it for `SAVE`. This PR fixes this bug for `OPEN_FILE` and `OPEN_DIRECTORY` too. `OPEN_MULTIPLE` always had the null check, and never crashed.
**This error is Hashlink only.**
(stack trace of that error:)
```
Uncaught exception: Access violation
Called from $String.fromUTF8(C:\HaxeToolkit\haxe\std/hl/_std/String.hx:240)
Called from lime.ui.FileDialog.~browse.1(lime/ui/FileDialog.hx:152)
Called from lime.app._Event_Dynamic_Void.dispatch(lime/_internal/macros/EventMacro.hx:91)
Called from lime.system.BackgroundWorker.__doWork(lime/system/BackgroundWorker.hx:115)
Called from lime.system.BackgroundWorker.run(lime/system/BackgroundWorker.hx:67)
Called from …
```
> Fix Segementation Faults When Canceling File/Directory browsing

- src/lime/tools/IconHelper.hx
Instead, assume that any icon without a specified size can scale freely. (This will typically still include SVGs.)
This change is meant to address #1576 and similar situations, where a low-priority SVG overrides a high-priority PNG. With this change, the image types are treated equally, so priority becomes the deciding factor.
> Don't prioritize SVG icons.

- src/lime/utils/AssetLibrary.hx
[According to OpenFL's documentation](https://github.com/openfl/openfl/blob/d135dca3112d2688a2743653abb19fcebeef23f7/src/openfl/utils/Assets.hx#L373), `type` is "The asset type to match, or null to match any type."
Closes #1252.
> Check all asset types if `type == null`.

- src/lime/system/Clipboard.hx
As reported in multiple issues, the Linux clipboard isn't very reliable. Based on my testing, it only starts working properly after `set_text()` is called, so I figured the easiest option was to ensure that that gets called without actually changing the text.
Downside is that it'll turn any rich text into plaintext, but that's why I modified `get_text()` rather than making an `__init__()` function. That way, we only overwrite the clipboard if the app actually needs it.
Closes #1298 and #1464.
> Work around unreliable clipboard on Linux.

- templates/cpp/static/Main.cpp
When building a Lime application in debug mode on Windows, the console subsystem is used and Windows looks for a `main` function. However, the `Main.cpp` file used when linking statically always defines a `WinMain` function regardless of whether the application is being built in debug mode.
This pull request adds an additional check in `Main.cpp` to define a `main` function instead of `WinMain` when building in debug mode.
> Fix `Main.cpp` template for `-static` `-debug` builds

- src/lime/system/CFFI.hx
- templates/haxe/ManifestResources.hx
It isn't always safe to assume `./` is the app directory, and removing that assumption opens up options.
`Sys.programPath()` requires at least Haxe 3.4, but I don't think Lime supports 3.3 anyway.
Resolves #1284.
> Allow running native apps from other directories.

- src/lime/system/JNI.hx
Plus, add documentation to help avoid the sort of confusion we saw in #1295. Also, closes #1295.
> Parse JNI class names more intelligently.

- .github/workflows/main.yml
GitHub has officially begun to [drop macOS 10.15 support](https://github.com/actions/runner-images/issues/5583), causing workflows to fail.
> Use macOS 11 for testing.

- tools/platforms/IOSPlatform.hx
Closes #1590.
Edit: changed the title because I'm not sure `Null<Int>` counts as a null pointer.
> Fix null value in `IOSPlatform`.

- src/lime/system/System.hx
Thanks to LeotomasMC for some assistance with this.
I noticed and was quite confused by the fact that certain things in Flixel failed to work on Linux, such as FlxG.openURL, which returned "xdg-open: unexpected argument '&'". This appears to fix that and seems to work quite fine, with that segment of Flixel now working once more.
May be good to have someone more qualified than I check this out before er... merging, as I'm not exactly the best programmer around.
> Fix openFile not working on Linux.

- .github/workflows/main.yml
As explained in #1601, GitHub is dropping support for macos-10.15, so we switched to macos-11. Now, however, there's a file conflict when Homebrew tries to install Python as a dependency of SQLite. The files in question are not the sort that get used in a CI run, so the simplest solution may be to delete them.
> Remove conflicting files.

- project/lib/custom/jpeg/jconfigint.h
SIZEOF_SIZE_T  needs to be 4  for Raspberrypi in lib/custom/jpeg/jconfigint.h
instead of 8 for other platforms, otherwise jpegs are not decoded properly.
This commit adds a conditional
```
#if defined(RASPBERRYPI)
#define SIZEOF_SIZE_T  4
#else
#define SIZEOF_SIZE_T  8
#endif
```
> Fix SIZEOF_SIZE_T in jpeg for RaspberryPi

- CHANGELOG.md
Currently everything is in chronological order, and I tried to mention every fix that an end user could notice. I'm taking suggestions about ordering and/or wording.
Oh yeah, and I cleaned up a bunch of whitespace to make [markdownlint](https://github.com/DavidAnson/markdownlint) stop complaining. This isn't required, but it'll make it easier to catch actual issues like in b9e46f947e6680061c7065910f4b5913e9510f77.
> Update changelog for 8.0.1

- .github/workflows/main.yml
Version 2 of these actions seems to rely on deprecated features.
We might be able to leave `download-artifact`, but it seems best to keep it in sync.
> Use v3 of `checkout` and `upload-artifact`.

- .github/workflows/main.yml
GitHub has officially begun to [drop Ubuntu 18.04 support](https://github.com/actions/runner-images/issues/6002), causing workflows to fail. As with Mac, we seem to be using the oldest available version to ensure compatibility, which is why I picked Ubuntu 20 instead of 22.
> Use Ubuntu 20 for testing.

- src/haxe/Timer.hx
- src/lime/_internal/backend/native/NativeApplication.hx
- src/lime/app/Promise.hx
This prevents an inconsistent "Field has no new expression" bug. A couple of us [spent hours trying to track this bug down](https://discord.com/channels/415681294446493696/457589935487189003/1096800407998709800), with limited success.
- It seems to be related to macros. For a while I thought it was specific to build macros, but eventually we confirmed that any macro can cause it.
- It seems to be related to [`WorkFunction.dispatch()`](https://github.com/openfl/lime/blob/45bc8c4aef6548a6fcb0f89555cab733052e80d8/src/lime/system/WorkOutput.hx#L263-L272) and [`JSAsync.async()`](https://github.com/openfl/lime/blob/45bc8c4aef6548a6fcb0f89555cab733052e80d8/src/lime/system/WorkOutput.hx#L391-L402), both of which are macros. Moving or changing these functions _sometimes_ fixes the issue.
- …
> Remove `@:generic` from `Promise` at macro time.

- src/lime/_internal/backend/html5/HTML5Window.hx
Using `userAgent` to tell whether the app is running on Android. This isn't foolproof, but will work more often than the previous approach (where you chose at compile time and your choice applied to all devices). Resolves #1655.
> Use "password" text input only on Android.

- src/lime/system/CFFI.hx
`substr(7)` returns the substring _starting_ at character 7, which will never be "windows". The author meant to type `substr(0, 7)` instead, to get the substring ending at 7.
We could easily make this change, but given that the code has been successfully using forward slashes for several years, I prefer to simplify.
> Use forward slashes to load lime.ndll.

- src/lime/tools/HXProject.hx
- tools/CommandLineTools.hx
I think I've mentioned before how included projects can't always get the data they need, and it came up again in #1486. It's incredibly easy to get the architectures in an HXP project, but there's just no way in XML, nor is there an elegant way to add support.
There's one issue to be aware of here: all paths in include.hxp will be relative to the main project, which is practically guaranteed to break local paths. So, you have to type out `Sys.getCwd() + "local/path"` each time. Not a deal-breaker, just something people will have to be aware of.
Oh yeah, I refactored a few things while I was at it. IMO, the whole function should have been named `fromDirectory()` in the first place, because otherwise it sounds the same as `fromFile()`. It's a little late to change that now, so I'll settle …
> Add support for include.hxp.

- project/src/media/openal/OpenALBindings.cpp
- src/lime/_internal/backend/native/NativeCFFI.hx
When calling `AL.filteri` with hashlink target we can see the error `INVALID_VALUE: Invalid parameter value` when checking for errors with `AL.getErrorString()`. This pull request fixes it.
There's a repo here which can be used to recreate the problem - https://github.com/jobf/lime-openal-efx-invalid-param-test
Run the project with `lime test hl` and click the lime window to hear the sound. Check the console to see the following
```
NativeAudioSource.hx:144: shadow source play
NativeAudioSource.hx:160: createFilter error ? 
NativeAudioSource.hx:163: filteri error ? INVALID_VALUE: Invalid parameter value
NativeAudioSource.hx:166: filterf LOWPASS_GAIN error ?INVALID_ENUM: Invalid enum value
NativeAudioSource.hx:169: filterf LOWPASS_GAINHF error ?INVALID_ENUM: Invalid enum value
```
Once the …
> Fix OpenAL binding AL.filteri for hashlink

- templates/android/template/app/src/main/java/org/haxe/lime/GameActivity.java
> Use `getDisplayMetrics()` to find screen DPI on Android.

- src/lime/_internal/backend/html5/HTML5Window.hx
**onDropFile** is dispatched for each files on native with the full path of the file as a parameter.
But in html5 it is only dispatched once with a FileList as a parameter which is an array.
Also this array doesn't give the full path, it is mandatory to call` js.html.URL.createObjectURL(file)` to get the full path.
So this commit allows to make the behavior across targets consistent.
Now `onDropFile `in the html5 target  is dispatched for each files and the full path is passed as a parameter like in the native target.
> make html5 behavior of onDropFile same as native

- src/lime/_internal/backend/html5/HTML5Application.hx
This way, changing the computer clock can't mess up animations. Resolves #1367.
There is a fallback if `window.performance` isn't available, and I left that intact.
---
I was going to update `Timer.stamp()` to use `self.performance`, because that's available in web workers as well as normal windows. It would look like this:
```diff
#elseif js
-return Date.now().getTime() / 1000;
+return js.Browser.self.performance.now() / 1000;
#elseif cpp
```
However, I later realized that I was editing the standard library version of `Timer`, and my changes would be overwritten the next time we updated it. So I'm leaving the change out, but perhaps it could be submitted upstream.
> Use `performance.now()` for HTML5 timing.

- src/lime/system/CFFI.hx
This message comes up relatively often when a new user tries to set up Lime, but fails to give any instructions a new user could use.
This commit adds a new message explaining the most common issue and how to solve it. It also provides file paths, which may help with more in-depth debugging.
> Improve "Could not find NekoAPI interface" message.

- src/lime/_internal/backend/html5/HTML5HTTPRequest.hx
- src/lime/graphics/Image.hx
Need to explicitly use:
new window.Image() 
otherwise it will create a lime Image object.
> Fixed JS Image issue when using the genes library to compile ES modules

- project/include/text/Font.h
- project/src/text/Font.cpp
Makes it clear that the string won't be modified, and avoids needing to cast away const when passing const char pointers into these methods.
> Take const char pointers in lime::Font methods
