lime/tools/helpers/HTML5Helper.hx

http://community.openfl.org/t/openfl-html5-minify-throwing-error/750

Change rename into copy + delete

---

project/src/audio/openal/OpenALBindings.cpp

Fixes OpenAL initialization on Node.js

Fix null check in lime_alc_open_device

---

lime/_backend/native/NativeApplication.hx
lime/graphics/Image.hx
lime/graphics/format/PNG.hx
lime/graphics/opengl/GL.hx
lime/system/System.hx
lime/utils/ByteArray.hx
project/src/graphics/ImageBuffer.cpp
templates/haxe/DefaultAssetLibrary.hx
templates/nodejs/hxml/debug.hxml
templates/nodejs/hxml/final.hxml
templates/nodejs/hxml/release.hxml

Number of fixes to use Node.js as a target.

Node.js-related fixes

---

lime/tools/helpers/HTML5Helper.hx

to access html5 projects tested locally from other devices by entering server IP

start node server on 0.0.0.0 instead of localhost

---

lime/tools/platforms/FlashPlatform.hx

https://github.com/openfl/lime/issues/376

fix for new haxe 3.2 Sys.command escaping

---

project/src/ExternalInterface.cpp

Don't alloc string on null char* directory

---

haxe/Timer.hx
lime/text/Font.hx

These lines caused compile errors on nodejs.

Fix compile error on nodejs

---

lime/audio/AudioSource.hx

See: https://github.com/openfl/openfl/pull/605

Audio: SOUND_COMPLETE events, looping, pause/resume

---

lime/graphics/utils/ImageDataUtil.hx
project/include/graphics/ImageBuffer.h
project/src/graphics/Image.cpp
project/src/graphics/ImageBuffer.cpp
project/src/graphics/utils/ImageDataUtil.cpp

Fixes issue https://github.com/openfl/openfl/issues/618

Fixes copyPixels mergeAlpha

---

lime/Assets.hx

Same as https://github.com/openfl/openfl/pull/620

Font embedding file not found fix.

---

project/src/graphics/utils/ImageDataUtil.cpp

Fixes https://github.com/openfl/openfl/issues/631

Let's make a float division and not an integer one

---

lime/graphics/utils/ImageDataUtil.hx
project/src/graphics/utils/ImageDataUtil.cpp

Fixes https://github.com/openfl/openfl/issues/635

Implement correct alpha blending for copyPixels

---

project/src/audio/format/OGG.cpp

Reduced the number of ByteArray resizing needed to load an Ogg Vorbis file.

Make Ogg vorbis loading faster

---

lime/audio/AudioSource.hx

fixes https://github.com/openfl/openfl/issues/746

fix audio offset

---

legacy/include.xml

Similar to static link in "non-legacy". Sorry. I will try to merge the pull requests with Main.cpp and include.xml.

[Legacy] template for static link: include.xml

---

legacy/templates/cpp/static/Main.cpp

Similar to static link in "non-legacy". Sorry. I will try to merge the pull requests with Main.cpp and include.xml.

[Legacy] template for static link: Main.cpp

---

legacy/templates/cpp/static/BuildMain.xml

Similar to static link in "non-legacy". Sorry. I will try to merge the pull requests with Main.cpp and include.xml.

[Legacy] template for static link: BuildMain.xml

---

.travis.yml

Trying to convert .travis.yml to their new mode according to http://docs.travis-ci.com/user/migrating-from-legacy/

Use new travis mode

---

lime/graphics/opengl/GL.hx

c.f. https://github.com/openfl/openfl/pull/803

blend mode support

---

legacy/project/src/iPhone/UIStageView.mm

It's strange why touches parameter passed to the methods doesn't have all touches. But this fix works for me.

Fix the multitouch support on iOS

---

legacy/project/src/ExternalInterface.cpp
lime/_backend/flash/FlashWindow.hx
lime/_backend/html5/HTML5Window.hx
lime/_backend/native/NativeWindow.hx
lime/ui/Window.hx
project/include/ui/Window.h
project/src/ExternalInterface.cpp
project/src/backend/sdl/SDLWindow.cpp
project/src/backend/sdl/SDLWindow.h

plus a hacked-in function for legacy

Added window flashing alert function under window class

---

project/src/backend/sdl/SDLApplication.cpp

solves https://github.com/openfl/openfl/issues/815

Neutralize SDL_FINGERUP on Mac OSX

---

lime/_backend/native/NativeApplication.hx

touch = new Touch (touchEventInfo.x, touchEventInfo.x, ...
must be
touch = new Touch (touchEventInfo.x, touchEventInfo.y, ...

Touch bug on iOS, problem not solved

---

lime/project/ProjectXMLParser.hx

This makes it possible to have optional dependencies.

ProjectXMLParser: add a validate attribute to <haxelib>

---

templates/iphone/PROJ.xcodeproj/project.pbxproj

Makes included examples build again.

Added missing dependency for IOS

---

lime/tools/platforms/TVOSPlatform.hx
templates/iphone/PROJ/PROJ-Info.plist
templates/tvos/PROJ/PROJ-Info.plist

Add NSAppTransportSecurity section to info.plist with NSAllowsArbitraryLoads enabled

Add NSAppTransportSecurity section to info.plist with NSAllowsArbitraryLoads enabled

---

lime/Assets.hx

See https://github.com/openfl/openfl/issues/587
continuation of https://github.com/openfl/openfl/commit/add551b650304d24c49374be0ef8a959cded1286

Print callstack when asset not found in debug mode

---

tools/CommandLineTools.hx

And additional questions - for what purpose exists opera and chrome templates in the templates directory? These are used with flags ```-opera``` and ```-chrome``` ? I tried to do ```lime test flash -opera``` but the result is steel the same as just ```lime test flash```.

Add help info for -web flag

---

templates/android/template/app/src/main/AndroidManifest.xml

Write android:debuggable property only if it is true. That is solved my problem.

Android SDK gives error when android:debuggable="false"

---

lime/math/ColorMatrix.hx

See https://github.com/openfl/openfl/issues/1225#issuecomment-246741672

Special case for alpha ColorMatrix table

---

lime/system/Locale.hx

I had to remove the __init__ function and use getters & setters since calling JNI inside __init__  raised errors (I guess because JNI get loaded / initialized after a Locale).

Add lime.system.Locale implementation for Android using JNI

---

dependencies/extension-api/build.gradle
templates/android/template/build.gradle
templates/extension/dependencies/android/build.gradle

For some reason I hard-coded version 2.10. Oops!

Allow setting a different Gradle version.

---

lime/_backend/html5/HTML5HTTPRequest.hx

- Works for 'data:' URLs
- Works in IE11

Added better progress event logic:

---

lime/media/AudioBuffer.hx

... additionally fromBase64 method added to create a AudioBuffer from base64 string

Html5 support added in AudioBuffer's fromBytes method

---

lime/_backend/air/AIRWindow.hx

This is just a quick fix to make it work.

Quick fix for #1103

---

lime/tools/helpers/AIRHelper.hx
lime/tools/platforms/AIRPlatform.hx
templates/air/template/application.xml

`<dependency name="com.example.Extension1" path="Lib/Extension1.ane" if="air" />`

added support for native extensions for Adobe AIR

---

lime/_backend/native/NativeAudioSource.hx
lime/_backend/native/NativeCFFI.hx
lime/media/openal/AL.hx
lime/media/openal/ALAuxiliaryEffectSlot.hx
lime/media/openal/ALEffect.hx
lime/media/openal/ALFilter.hx
project/src/media/openal/OpenALBindings.cpp

It was already in there, I just exposed the API. It works, very nicely I might add :)
Also, this needs a documentation and some functions for ease of use. I mean not everyone knows what's an auxiliary send and how to use it :/ and OpenAL EFX loves those. Any suggestion on how to go about this?

OpenAL Effects Extension 

---

templates/android/template/build.gradle

This template file change is tested with the following extensions:
[extension-share](https://github.com/HaxeExtension/extension-share)
[extension-webview](https://github.com/HaxeExtension/extension-webview)
[camera](https://github.com/bazzisoft-openfl-extensions/camera)
[extension-firebase](https://github.com/HaxeExtension/extension-firebase)
And native text seen [here](https://github.com/PXshadow/App/tree/master/src/ext) in App extensions.

Changes to android template that allows Firebase extension to work.

---

src/lime/_internal/graphics/ImageDataUtil.hx

> from https://github.com/innogames/lime/pull/7
there were several issues here:
- `translatePixel` tried to un-premultiply alpha from colors when working with non-premultiplied images
- it used the already scaled-by-strength alpha for that
- it didn't care about whether the image was premultiplied when writing the value back
so, since the only usage of this function in our openfl is on non-premultiplied images, and it didn't work correctly anyway, i just added a `throw` for the premultiplied bitmaps, which is arguably better than breaking them silently
and of course, now when it's sure it works with non-premultiplied images, it can just extract color directly, so `translatePixel` is simplier and doesn't screw up the colors, which fixes artifacts/wrong colors we see when using …

fix gaussianBlur filter messing up colors and alpha

---

lime/media/openal/AL.hx

http://community.openfl.org/t/reverb-with-openal-in-windows-build/10775/3

fix source3i value1 type

---

templates/electron/haxe/ElectronSetup.hx
templates/electron/hxml/debug.hxml
templates/electron/hxml/final.hxml
templates/electron/hxml/release.hxml

Amend hxml templates and rename Electron.hx to ElectronSetup.hx to make it more clear what it does

Electron Template Files Update

---

src/lime/_internal/graphics/ImageDataUtil.hx

With optional, bilinear filtering. This may be an initial implementation for now. Can be improved later on.

Method for software Displacement Map Filtering

---

src/lime/_internal/graphics/ImageDataUtil.hx

This swap makes Blur actually work - otherwise it does not display at all.

Swapped imgB and imgA back

---

templates/winrt/scripts/newcertificate.ps1
templates/winrt/temp/layout.resfiles
templates/winrt/temp/priconfig.xml
tools/platforms/WindowsPlatform.hx

Outputs Appx file, needs 2 manual steps:
1. Modify `sdkVersion` variable in WindowsPlatform.hx to the one you want to use for bin tools in `C:\Program Files (x86)\Windows Kits\10\bin\` and do `openfl rebuild tools`
2. For creating the certificate, Powershell command fails but the command lets you know which command you need to execute (copy and paste in the cmd prompt)
Tested with
```
lime rebuild winrt -static -Dcairo -m64
openfl test project.xml winrt -static -Dcairo -appx
```
should be created with the name and password used in the certificate tag in xml 
```
<certificate path="DisplayingABitmap" password="openflexample" if="winrt" />
```

Initial Winrt -appx

---

src/lime/utils/AssetLibrary.hx

Fix issue where http[s] paths were changing to relative paths when loading assets.

Fix issue where http root paths were being converted to relative paths

---

project/Build.xml
tools/platforms/AndroidPlatform.hx

Minor fixes for the android x86_64 build

Added correct platform for android x86_64 builds

---

.github/workflows/main.yml

Doesn't yet build any sample projects, but this feels like a good start.

Github Actions: Fix builds that are currently failing, add android target, and add a matrix of Haxe versions

---

.github/workflows/main.yml

Currently, does not include iOS, but I plan to add that later.
I also consolidated everything into a single job with the operating systems added to the matrix instead of separate jobs for each operating system, which helps avoid too much duplication.

Github Actions: also compiles some samples for a bunch of platforms

---

src/lime/_internal/backend/html5/HTML5Window.hx

Fix IEM Input text. 
Before, when inputting Chinese, the text displayed: ni'hao你好
Now: 你好

Fix IEM Input text

---

templates/android/template/app/src/main/java/org/libsdl/app/SDLActivity.java

Solution to [https://community.openfl.org/t/100-bounty-touch-not-working-on-some-google-pixel-phones/12818](https://community.openfl.org/t/100-bounty-touch-not-working-on-some-google-pixel-phones/12818)

Fix Touch not working on some Google Pixel phones

---

templates/electron/haxe/ElectronSetup.hx

Compatible with electron version 11.
The issues : https://github.com/electron/electron/issues/17241

Compatible with electron version 11.

---

templates/android/template/app/build.gradle

I got error, when tried to build and sign my project for Android and I fixed it

Fixed build for Android when signing

---

project/src/backend/sdl/SDLApplication.cpp

https://github.com/HaxeFoundation/hxcpp/issues/969#issuecomment-941127280

Fix GC issues on iOS 15 with iPhone 12

---

tools/platforms/AndroidPlatform.hx

For parity with #1519, and to resolve #757.

Set minimum-sdk-version to 21.

---

src/lime/_internal/backend/native/NativeAudioSource.hx

`vorbisFile.timeTell()` returns the current decoding offset in seconds,
and it's updated each time `vorisFile.read()` is called. Since data is
buffered by calling `vorbisFile.read()` multiple times, the associated
time values also need to be preserved in order to get the correct time
offset.
Without this change, `getCurrentTime()` will return some time in the
future relative to the amount of buffered data.

Fix getCurrentTime for streaming native sounds

---

project/src/media/codecs/vorbis/VorbisFile.cpp

vorbisfile.cpp - change free(x) to `delete x` (fixes #1556)

vorbisfile.cpp - change free(x) to `delete x` (fixes #1556)

---

src/lime/_internal/backend/html5/HTML5AudioSource.hx

NPE was occurring in setPosition where parent.buffer was undefined.

Catch null pointer exception

---

src/lime/system/JNI.hx

Fix error when using JNI in macro context.

---

src/lime/app/Future.hx

The error might not even be RPi-specific. As far as I can tell, the issue is that due to [`@:generic`](https://haxe.org/manual/type-system-generic.html), `Promise<Dynamic>` is its own class, distinct from whatever type got created earlier, so we can't cast between the two. And static targets have some kind of enforcement mechanism, so when we try to store the other promise as a `Promise<Dynamic>`, it just stores null.
I don't think the `@:generic` metadata is needed, but I'm not about to remove it without knowing why it was added. So instead, I chose to store the specific functions we need, since those shouldn't have any trouble with casting.

Fix null pointer error on RPi.

---

src/lime/system/JNI.hx

i recently noticed that in JNI.hx that was done in a really weird way that was making arguements limit. I tested those changes and it seems to work fine

remove arguements limit in jni
